[tool.poetry]
name = "frast"
version = "0.1.0"
description = ""
authors = ["Jackson Greene <jackson.greene@student.curtin.edu.com>"]
readme = "README.md"

[tool.poetry.scripts]
frast = "frast.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.4.1"}
requests = {extras = ["all"], version = "^2.27.1"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
