name: publish

on:
  push:
    branches:
      # Release branches.
      # Examples: "v1", "v3.0", "v1.2.x", "1.5.0", "1.2rc0"
      # Expected usage is (for example) a branch named "v1.2.x" which contains
      # the latest release in the 1.2 series.
      - "v[0-9]+"
      - "v?[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9x]+rc[0-9]*"
    tags:
      # Run whenever any tag is created
      - "v[0-9]+"
      - "v?[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9x]+rc[0-9]*"
  pull_request:
    branches:
      # Release branches
      - "v[0-9]+"
      - "v?[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9]+.[0-9]+.[0-9x]+"
      - "v?[0-9]+.[0-9x]+rc[0-9]*"

jobs:
  build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 setuptools_scm

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
