#Cluster status:
cluster_health:
  cmd_type: "rest"
  cmd: "/_cluster/health?pretty"
  file: "cluster_health.json"


cluster_settings:
  cmd_type: "rest"
  cmd: "/_cluster/settings?pretty&flat_settings"
  file: "cluster_settings.json"

cluster_settings_default:
  cmd_type: "rest"
  cmd: "/_cluster/settings?include_defaults&pretty&flat_settings"
  file: "cluster_settings_default.json"

cluster_state:
  cmd_type: "rest"
  cmd: "/_cluster/state?pretty&human"
  file: "cluster_state.json"


cluster_stats:
  cmd_type: "rest"
  cmd: "/_cluster/stats?pretty&human"
  file: "cluster_stats.json"

#Nodes
master:
  cmd_type: "rest"
  cmd: "/_cat/master?format=json"
  file: "master.json"

nodes_cat:
  cmd_type: "rest"
  cmd: "/_cat/nodes?format=json"
  file: "nodes_cat.json"

nodes_cat_table:
  cmd_type: "rest"
  cmd: "/_cat/nodes?v"
  file: "nodes_cat_table.csv"

nodes:
  cmd_type: "rest"
  cmd: "/_nodes?pretty&human"
  file: "nodes.json"

nodes_stats:
  cmd_type: "rest"
  cmd: "/_nodes/stats?pretty&human"
  file: "nodes_stats.json"

nodes_usage:
  cmd_type: "rest"
  cmd: "/_nodes/usage?pretty"
  file: "nodes_usage.json"

nodes_hot_threads:
  cmd_type: "rest"
  cmd: "/_nodes/hot_threads"
  file: "nodes_hot_threads.json"

thread_pool_table:
  cmd_type: "rest"
  cmd: "/_cat/thread_pool?v"
  file: "thread_pool_table.csv"

#Index
indices:
  cmd_type: "rest"
  cmd: "/_cat/indices?format=json&bytes=b"
  file: "indices.json"

indices_table:
  cmd_type: "rest"
  cmd: "/_cat/indices?bytes=b&v"
  file: "indices_table.csv"

hot_indices_table:
  cmd_type: "rest"
  cmd: "/_cat/indices/_hot?bytes=b&v"
  file: "hot_indices_table.csv"

warm_indices_table:
  cmd_type: "rest"
  cmd: "/_cat/indices/_warm?bytes=b&v"
  file: "warm_indices_table.csv"

indices_stats:
  cmd_type: "rest"
  cmd: "/_stats?level=shards&pretty&human"
  file: "indices_stats.json"


#Field
fielddata:
  cmd_type: "rest"
  cmd: "/_cat/fielddata?format=json&bytes&pretty"
  file: "fielddata.json"

fielddata_stats:
  cmd_type: "rest"
  cmd: "/_nodes/stats/indices/fielddata?level=shards&pretty=true&fields=*"
  file: "fielddata_stats.json"

#Mapping
mapping:
  cmd_type: "rest"
  cmd: "/_mapping?pretty"
  file: "mapping.json"


#Allocation
allocation:
  cmd_type: "rest"
  cmd: "/_cat/allocation?v&format=json"
  file: "allocation.json"

allocation_table:
  cmd_type: "rest"
  cmd: "/_cat/allocation?v&bytes=b"
  file: "allocation_table.csv"

allocation_explain:
  cmd_type: "rest"
  cmd: "/_cluster/allocation/explain?pretty"
  file: "allocation_explain.json"

allocation_help:
  cmd_type: "rest"
  cmd: "/_cat/allocation?help"
  file: "allocation_help.txt"

#Shard
shards:
  cmd_type: "rest"
  cmd: "/_cat/shards?format=json&bytes=b&pretty"
  file: "shards.json"

shards_table:
  cmd_type: "rest"
  cmd: "/_cat/shards?v"
  file: "shards_table.csv"

hot_shards_table:
  cmd_type: "rest"
  cmd: "/_cat/shards/_hot?v"
  file: "hot_shards_table.csv"

warm_shards_table:
  cmd_type: "rest"
  cmd: "/_cat/shards/_warm?v"
  file: "warm_shards_table.csv"

shards_help:
  cmd_type: "rest"
  cmd: "/_cat/shards?help"
  file: "shards_help.txt"

shards_detail:
  cmd_type: "rest"
  cmd: "/_cat/shards?format=json&bytes=b&s=index&h=index,shard,prirep,state,docs,store,id,node,se,sm,fm,fe,ft,iiti,iito,iitf,idto,idti,ftt,ua,ud,ur"
  file: "shards_detail.json"

shards_detail_table:
  cmd_type: "rest"
  cmd: "/_cat/shards?v&bytes=b&s=index&h=index,shard,prirep,state,docs,store,id,node,se,sm,fm,fe,ft,iiti,iito,iitf,idto,idti,ftt,ua,ud,ur"
  file: "shards_detail_table.csv"

shard_stores:
  cmd_type: "rest"
  cmd: "/_shard_stores?pretty"
  file: "shard_stores.json"

#Tasks
tasks:
  cmd_type: "rest"
  cmd: "/_tasks"
  file: "tasks.json"

pending_tasks:
  cmd_type: "rest"
  cmd: "/_cluster/pending_tasks"
  file: "pending_tasks.json"

pending_tasks_table:
  cmd_type: "rest"
  cmd: "/_cat/pending_tasks?v"
  file: "pending_tasks_table.csv"

recovery_table:
  cmd_type: "rest"
  cmd: "/_cat/recovery?v"
  file: "recovery_table.csv"

#Open Distro
monitor_stats:
  cmd_type: "rest"
  cmd: "/_opendistro/_alerting/stats"
  file: "monitor_stats.json"

domain_config:
  cmd_type: "method"
  cmd: "domain_config"
  need_params: true
  file: "domain_config.txt"

script_version:
  cmd_type: "method"
  cmd: "script_version"
  need_params: false
  file: "script_version.txt"