[tool.poetry]
name = "aoricaan-cli"
version = "0.3.0"
description = ""
authors = ["carlos <carlosaarivera23@gmail.com>"]
readme = 'README.md'

[tool.poetry.scripts]
apm = 'aoricaan_cli.cli:app'

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.4.1"}
python-dotenv = "^0.19.1"
pydantic = "^1.8.2"
tqdm = "^4.62.3"
click-spinner = "^0.1.10"
tabulate = "^0.8.9"
uvicorn = "^0.16.0"
fastapi = "^0.71.0"
mangum = "^0.12.3"
cookiecutter = "^1.7.3"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^8.0.0"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
