[tool.poetry]
name = "dj-spoofer"
version = "0.1.6"
description = "Django + Web Scraping Made Easy"
authors = ["Adrian <adrian@rydeas.com>"]
repository = "https://github.com/adrianmeraz/dj-spoofer"
packages = [
    { include = "djspoofer" }
]
exclude = [
    "manage.py"
]

[tool.poetry.dependencies]
python = "^3.9"

coverage = "^6.2"
Django = "^3.2.4"
django-environ = "^0.8.1"
django-import-export = "^2.8.0"
Faker = "~8.12.1"
httpx = {version = "~0.22.0", extras = ["http2"]}
psycopg2-binary = "^2.9.2"
python-dotenv = "^0.19.0"
wheel = "^0.36.2"
dj-starter = "^0.1.11"
ua-parser = "^0.10.0"
urllib3 = "^1.26.9"

[tool.poetry.dev-dependencies]
respx = "~0.19.0"
tblib = "~1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
