[tool.poetry]
name = "flask_admin_plus"
version = "1.6.3"
description = "Flask Admin with a few more features and improvements"
authors = ["Sean McCarthy <smccarthy@myijack.com>"]
packages = [
    { include = "flask_admin" },
]

[tool.poetry.dependencies]
python = ">=3.7,<3.12"

[tool.poetry.dev-dependencies]
Flask = "^2.1.2"
python-dotenv = "^0.20.0"
flask-redis = "^0.4.0"
Flask-SQLAlchemy = "^2.5.1"
WTForms = "^3.0.1"
MarkupSafe = "^2.1.1"
flake8 = "^4.0.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
