[tool.poetry]
name = "cloudops_google_bigquery"
version = "0.1.1"
description = ""
authors = ["Manuel Castillo <manucalop@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-bigquery = "^3.1.0"
pandas = "^1.4.2"
pandas-gbq = "^0.17.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
