[build-system]
requires = ["setuptools>=62.3.2", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "yamongo"
version = "0.0.2"
description = "Easy to use access to MongoDb databases for basic operations"
readme = "README.md"
authors = [{ name = "Joakim Wassberg", email = "joakim@arthead.se" }]

keywords = ["MongoDB", "Database", "pymongo"]
dependencies = [
    "pymongo >= 4.1.1",
]

requires-python = ">=3.6.2"

[project.urls]
Homepage = "https://github.com/arthead-development/yamongo"
