[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pigeonly-address"
version = "0.0.1"
description = "Address Standardization"
readme = "README.md"
authors = [{ name = "Peter Flynn", email = "peterflynn@pigeon.ly" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["address"]
dependencies = [
    "lxml",
    "xmltodict",
    "requests",
]
requires-python = ">=3.6"

[project.optional-dependencies]
dev = ["black", "isort", "flake8", "radon", "pre-commit", "pytest", "pytest-mock"]

[project.urls]
Homepage = "https://gitlab.pigeon.ly/pflynn/pigeonly-address"
