# pyproject.toml

[build-system]
requires      = ["setuptools>=62.3.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python_easy_aes"
version = "1.0.0"
description = "Easily encrypt/decrypt files/texts using AES"
readme = "README.md"
authors = [{ name = "Aria Bagheri", email = "ariab9342@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["python", "AES", "AES-256"]
dependencies = [
    "pycryptodome==3.14.1"
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/AriaBagheri/python_easy_aes"

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"src/easy_aes/__init__.py" = ["{version}"]
