[tool.poetry]
name = "mypyliextester"
version = "22.06.01-6"
description = "Project description"
authors = ["Tadeusz Miszczyk <tadeusz.miszczyk@bshg.com>"]
homepage = "http://github.com/8tm/my_python_library_example_tester"
documentation = "https://test.pypi.org/project/my_python_library_example_tester"
repository = "http://github.com/8tm/my_python_library_example_tester"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: Unix",
]


[tool.poetry.dependencies]
mypyliex = "22.06.01-4"

[tool.poetry.dev-dependencies]
pip-search = "^0.0.7"


[tool.poetry.scripts]
my_python_library_example_tester = 'mypyliextester.main:main'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
