METIS_DO_NOT_TRACK_COMMENT = "/*METIS_DO_NOT_TRACK*/"

METIS_REQUEST_SPAN_ATTRIBUTE_IDENTIFIER = "track.by.metis"
METIS_PLAN_SPAN_ATTRIBUTE = "metis.statement.plan"
METIS_STATEMENT_SPAN_ATTRIBUTE = "metis.statement"

METIS_QUERY_SPAN_NAME = "metis-query"
