[tool.poetry]
name = "hymaia-cli"
version = "1.0.1"
description = ""
authors = ["Elhadi Cherifi <elhadi.cherifi@hymaia.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hymaia_cli = "hymaia_cli.main:main"
