"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.hyperparameter_tuning_pb2
import layerapi.api.entity.model_train_status_pb2
import layerapi.api.ids_pb2
import layerapi.api.value.aws_credentials_pb2
import layerapi.api.value.hyperparameter_tuning_metadata_pb2
import layerapi.api.value.s3_path_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StartModelTrainingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> None: ...
global___StartModelTrainingRequest = StartModelTrainingRequest

class StartModelTrainingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___StartModelTrainingResponse = StartModelTrainingResponse

class CancelModelTrainingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    @property
    def model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_train_id",b"model_train_id"]) -> None: ...
global___CancelModelTrainingRequest = CancelModelTrainingRequest

class CancelModelTrainingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___CancelModelTrainingResponse = CancelModelTrainingResponse

class GetSourceCodeUploadCredentialsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_NAME_FIELD_NUMBER: builtins.int
    source_name: typing.Text
    def __init__(self,
        *,
        source_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["source_name",b"source_name"]) -> None: ...
global___GetSourceCodeUploadCredentialsRequest = GetSourceCodeUploadCredentialsRequest

class GetSourceCodeUploadCredentialsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CREDENTIALS_FIELD_NUMBER: builtins.int
    S3_PATH_FIELD_NUMBER: builtins.int
    @property
    def credentials(self) -> api.value.aws_credentials_pb2.AwsCredentials: ...
    @property
    def s3_path(self) -> api.value.s3_path_pb2.S3Path: ...
    def __init__(self,
        *,
        credentials: typing.Optional[api.value.aws_credentials_pb2.AwsCredentials] = ...,
        s3_path: typing.Optional[api.value.s3_path_pb2.S3Path] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["credentials",b"credentials","s3_path",b"s3_path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["credentials",b"credentials","s3_path",b"s3_path"]) -> None: ...
global___GetSourceCodeUploadCredentialsResponse = GetSourceCodeUploadCredentialsResponse

class GetModelTrainStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.ModelTrainId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___GetModelTrainStatusRequest = GetModelTrainStatusRequest

class GetModelTrainStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRAIN_STATUS_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    FINISH_TIME_FIELD_NUMBER: builtins.int
    @property
    def train_status(self) -> api.entity.model_train_status_pb2.ModelTrainStatus: ...
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finish_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        train_status: typing.Optional[api.entity.model_train_status_pb2.ModelTrainStatus] = ...,
        start_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finish_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finish_time",b"finish_time","start_time",b"start_time","train_status",b"train_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["finish_time",b"finish_time","start_time",b"start_time","train_status",b"train_status"]) -> None: ...
global___GetModelTrainStatusResponse = GetModelTrainStatusResponse

class CreateHyperparameterTuningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_VERSION_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def model_version_id(self) -> api.ids_pb2.ModelVersionId: ...
    data: typing.Text
    def __init__(self,
        *,
        model_version_id: typing.Optional[api.ids_pb2.ModelVersionId] = ...,
        data: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_version_id",b"model_version_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","model_version_id",b"model_version_id"]) -> None: ...
global___CreateHyperparameterTuningRequest = CreateHyperparameterTuningRequest

class CreateHyperparameterTuningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___CreateHyperparameterTuningResponse = CreateHyperparameterTuningResponse

class GetHyperparameterTuningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___GetHyperparameterTuningRequest = GetHyperparameterTuningRequest

class GetHyperparameterTuningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning(self) -> api.entity.hyperparameter_tuning_pb2.HyperparameterTuning: ...
    def __init__(self,
        *,
        hyperparameter_tuning: typing.Optional[api.entity.hyperparameter_tuning_pb2.HyperparameterTuning] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning",b"hyperparameter_tuning"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning",b"hyperparameter_tuning"]) -> None: ...
global___GetHyperparameterTuningResponse = GetHyperparameterTuningResponse

class UpdateHyperparameterTuningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    OUTPUT_MODEL_TRAIN_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    FINISH_TIME_FIELD_NUMBER: builtins.int
    STATUS_INFO_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    data: typing.Text
    @property
    def output_model_train_id(self) -> api.ids_pb2.ModelTrainId: ...
    status: api.entity.hyperparameter_tuning_pb2.HyperparameterTuning.Status.ValueType
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finish_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    status_info: typing.Text
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        data: typing.Text = ...,
        output_model_train_id: typing.Optional[api.ids_pb2.ModelTrainId] = ...,
        status: api.entity.hyperparameter_tuning_pb2.HyperparameterTuning.Status.ValueType = ...,
        start_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finish_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        status_info: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finish_time",b"finish_time","hyperparameter_tuning_id",b"hyperparameter_tuning_id","output_model_train_id",b"output_model_train_id","start_time",b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","finish_time",b"finish_time","hyperparameter_tuning_id",b"hyperparameter_tuning_id","output_model_train_id",b"output_model_train_id","start_time",b"start_time","status",b"status","status_info",b"status_info"]) -> None: ...
global___UpdateHyperparameterTuningRequest = UpdateHyperparameterTuningRequest

class UpdateHyperparameterTuningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text
    def __init__(self,
        *,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message"]) -> None: ...
global___UpdateHyperparameterTuningResponse = UpdateHyperparameterTuningResponse

class StartHyperparameterTuningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___StartHyperparameterTuningRequest = StartHyperparameterTuningRequest

class StartHyperparameterTuningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___StartHyperparameterTuningResponse = StartHyperparameterTuningResponse

class CancelHyperparameterTuningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___CancelHyperparameterTuningRequest = CancelHyperparameterTuningRequest

class CancelHyperparameterTuningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___CancelHyperparameterTuningResponse = CancelHyperparameterTuningResponse

class GetHyperparameterTuningStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___GetHyperparameterTuningStatusRequest = GetHyperparameterTuningStatusRequest

class GetHyperparameterTuningStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_STATUS_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    FINISH_TIME_FIELD_NUMBER: builtins.int
    STATUS_INFO_FIELD_NUMBER: builtins.int
    hyperparameter_tuning_status: api.entity.hyperparameter_tuning_pb2.HyperparameterTuning.Status.ValueType
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finish_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    status_info: typing.Text
    def __init__(self,
        *,
        hyperparameter_tuning_status: api.entity.hyperparameter_tuning_pb2.HyperparameterTuning.Status.ValueType = ...,
        start_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finish_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        status_info: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finish_time",b"finish_time","start_time",b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["finish_time",b"finish_time","hyperparameter_tuning_status",b"hyperparameter_tuning_status","start_time",b"start_time","status_info",b"status_info"]) -> None: ...
global___GetHyperparameterTuningStatusResponse = GetHyperparameterTuningStatusResponse

class StoreHyperparameterTuningMetadataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    @property
    def metadata(self) -> api.value.hyperparameter_tuning_metadata_pb2.HyperparameterTuningMetadata: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        metadata: typing.Optional[api.value.hyperparameter_tuning_metadata_pb2.HyperparameterTuningMetadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id","metadata",b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id","metadata",b"metadata"]) -> None: ...
global___StoreHyperparameterTuningMetadataRequest = StoreHyperparameterTuningMetadataRequest

class StoreHyperparameterTuningMetadataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text
    def __init__(self,
        *,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message"]) -> None: ...
global___StoreHyperparameterTuningMetadataResponse = StoreHyperparameterTuningMetadataResponse

class GetOrCreateLatestPendingHyperparameterTuningIdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_VERSION_ID_FIELD_NUMBER: builtins.int
    @property
    def model_version_id(self) -> api.ids_pb2.ModelVersionId: ...
    def __init__(self,
        *,
        model_version_id: typing.Optional[api.ids_pb2.ModelVersionId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_version_id",b"model_version_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_version_id",b"model_version_id"]) -> None: ...
global___GetOrCreateLatestPendingHyperparameterTuningIdRequest = GetOrCreateLatestPendingHyperparameterTuningIdRequest

class GetOrCreateLatestPendingHyperparameterTuningIdResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HYPERPARAMETER_TUNING_ID_FIELD_NUMBER: builtins.int
    @property
    def hyperparameter_tuning_id(self) -> api.ids_pb2.HyperparameterTuningId: ...
    def __init__(self,
        *,
        hyperparameter_tuning_id: typing.Optional[api.ids_pb2.HyperparameterTuningId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hyperparameter_tuning_id",b"hyperparameter_tuning_id"]) -> None: ...
global___GetOrCreateLatestPendingHyperparameterTuningIdResponse = GetOrCreateLatestPendingHyperparameterTuningIdResponse
