[tool.poetry]
name = "geoenv-cli"
version = "0.1.0"
description = "CLI for managing a docker based geospatial environment."
authors = ["Dustin Sampson <gridcell@gmail.com>"]
license = "MIT"
packages = [
    { include = "geoenv" }
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
geoenv = "geoenv.geoenv:main"