[tool.poetry]
name = "betterenv"
version = "1.0.0"
description = "A custom environment library"
authors = ["The Artful Bodger <theartfulbodger@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
