- id: blackish
  name: blackish
  description: "blackish: The uncompromising Python code formatter"
  entry: blackish
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
- id: blackish-jupyter
  name: blackish-jupyter
  description:
    "blackish: The uncompromising Python code formatter (with Jupyter Notebook support)"
  entry: blackish
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi, jupyter]
  additional_dependencies: [".[jupyter]"]
