[tool.poetry]
name = "nonebot_plugin_tweetPusher"
version = "0.0.2"
description = "a tweet pusher plugin for nonebot2"
authors = ["Kizureina"]
license = "MIT"
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"