[tool.poetry]
name = "cloudops-google-secretmanager"
version = "0.1.0"
description = ""
authors = ["Manuel Castillo <manucalop@gmail.com>"]
packages = [{include = "cloudops_google_secretmanager"}]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-secret-manager = "^2.11.0"
google-crc32c = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
