[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comperm"
version = "2022.6.0"
description = "Combination and permutation operations."
readme = "README.md"
authors = [
    { name = "谢方圆 (XIE Fangyuan)", email = "xie.fangyuan@foxmail.com" }
]
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
keywords = [
    "combination",
    "permutation",
]
dependencies = []
requires-python = ">=3.10"

[project.urls]
Homepage = "https://gitee.com/xie-fangyuan/comperm"

# initialize: `bumpver init`
# update preview: `bumpver update --patch --dry`
# update: `bumpver update --patch`
[tool.bumpver]
current_version = "2022.6.0"
version_pattern = "YYYY.MM.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"README.md" = [
    "{version}",
]
"src/comperm/__init__.py" = [
    "{version}",
]


# `pip install build twine`
#