[tool.poetry]
name = "subsplease-rss"
version = "0.1.0"
description = "SubsPlease RSS Helper"
authors = ["SlavWolf <git@slavwolf.dev>"]

[tool.poetry.dependencies]
python = "~3.10"
feedparser = "^6.0.10"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = {extras = ["toml"], version = "^5.0.1"}
pytest-cov = "^2.12.1"
nox = "^2022.1.7"
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-annotations = "^2.9.0"
flake8-bandit = "^3.0.0"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.4.25"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
darglint = "^1.8.1"
safety = "^1.10.3"
mypy = "^0.960"
pytype = "^2022.5.19"
codecov = "^2.1.12"
xdoctest = "^1.0.0"
typeguard = "^2.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["subsplease_rss"]

[tool.coverage.report]
show_missing = true
fail_under = 100