
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-30T07:48:40-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "ced1f64f934bffbf4659a4b57f1d9c62b81916a3",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
