
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-05T02:38:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0428f5a29f1fdc577f2c558490266d9db00583e3",
 "version": "0.9.dev2223"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
