---
#
# Test configuration for Onionprobe.
# Content may vary and endpoints selected usually have descriptor or connection errors.
#

circuit_stream_timeout: 60
control_port: 19051
descriptor_max_retries: 5
descriptor_timeout: 30
endpoints:
  Impffrei.work:
    address: 5sh6hmyvnm4nux5hibm7i3eakhzhdrs647ntv3ekuys2exskmtire4id.onion
    paths:
    - path: /
    port: 443
    protocol: https
  "Alexander F\xE6r\xF8y":
    address: lxwu7pwyszfevhglxfgaukjqjdk2belosfvsl2ekzx3vrboacvewc7qd.onion
    paths:
    - path: /
    port: 443
    protocol: https
http_connect_timeout: 30
http_read_timeout: 30
interval: 5
launch_tor: true
log_level: info
loop: true
new_circuit: false
prometheus_exporter: true
prometheus_exporter_port: 9935
randomize: true
shuffle: true
sleep: 5
socks_port: 19050
tor_address: 127.0.0.1
