[tool.black]

line-length = 120

target-version = ['py38']

include = '\.pyi?$'

exclude = '''

(

  /(

      \.eggs         # exclude a few common directories in the

    | \.git          # root of the project

    | \.hg

    | \.mypy_cache

    | \.tox

    | \.venv

    | _build

    | buck-out

    | build

    | dist

    | Docs

    | migrations

  )/

  | foo.py           # also separately exclude a file named foo.py in

                     # the root of the project

  | Docs/tasks.py

)

'''

#
#[tool.poetry]
#name = "mos_sdk"
#version = "0.1.0"
#description = ""
#authors = ["Your Name <you@example.com>"]
#
#[tool.poetry.dependencies]
#python = "^3.8"
#requests = "^2.27.1"
#matplotlib = "^3.5.1"
#numpy = "^1.22.3"
#pandas = "^1.4.2"
#PyYAML = "^6.0"
#gdspy = "^1.6.11"
#python-socketio = "^5.5.2"
#aiohttp = "^3.8.1"
#
#[tool.poetry.dev-dependencies]
#pytest = "7.1.1"
#coverage = "6.3.2"
#pre-commit = "^2.18.1"
#commitizen = "^2.24.0"
#black = "^22.3.0"
#flake8 = "^4.0.1"
#sphinx = "^4.5.0"
#sphinx-book-theme = "^0.3.2"
#
#[build-system]
#requires = ["poetry-core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"
#
#[[tool.poetry.source]]
#name = 'aliyun'
#url = "https://mirrors.aliyun.com/pypi/simple"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
