[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "flit-foobar-tddschn"
authors = [{name = "Xinyuan Chen", email = "45612704+tddschn@users.noreply.github.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[tool.flit.module]
name = "foobar"

[project.scripts]
flit-foobar-tddschn = "foobar.cli:main"