/* Generated by Cython 0.29.25 */

#ifndef __PYX_HAVE__NonameOrm__DB__DB
#define __PYX_HAVE__NonameOrm__DB__DB

#include "Python.h"

#ifndef __PYX_HAVE_API__NonameOrm__DB__DB

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C struct __pyx_obj_9NonameOrm_2DB_2DB_DB *instance;

#endif /* !__PYX_HAVE_API__NonameOrm__DB__DB */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initDB(void);
#else
PyMODINIT_FUNC PyInit_DB(void);
#endif

#endif /* !__PYX_HAVE__NonameOrm__DB__DB */
