version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "16:55"
    open-pull-requests-limit: 10
    labels:
      - "changelog: skip"
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "changelog: skip"
      - "dependencies"
