
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-05T17:46:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "301d57d090c03e1ce6a2b6fc23d1af204256aad9",
 "version": "4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
