symlinks:
  bash:
    ~/.bash_profile: $MYPYDOTFILES/shell/bash/.bash_profile
    ~/.bashrc: $MYPYDOTFILES/shell/bash/.bashrc
    ~/.profile: $MYPYDOTFILES/shell/bash/.profile
  zsh:
    ~/.zlogin: $MYPYDOTFILES/shell/zsh/.zlogin
    ~/.zshenv: $MYPYDOTFILES/shell/zsh/.zshenv
    ~/.zshrc: $MYPYDOTFILES/shell/zim/.zshrc
  zim:
    ~/.zimrc: $MYPYDOTFILES/shell/zim/.zimrc
  git:
    ~/.gitattributes: $MYPYDOTFILES/tools/git/.gitattributes
    ~/.gitconfig: $MYPYDOTFILES/tools/git/.gitconfig
    ~/.gitignore_global: $MYPYDOTFILES/tools/git/.gitignore_global
  vim:
    ~/.vimrc: $MYPYDOTFILES/tools/editors/vim/.vimrc
  docker:
    ~/.docker/config.json: $MYPYDOTFILES/tools/docker/config.json


