[tool.poetry]
name = "gitreturntowork"
version = "0.0.5"
description = ""
authors = ["Brighten Tompkins <brightenqtompkins@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
PyInquirer = "^1.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
