[tool.poetry]
name = "clichessdrill"
version = "0.2.1"
description = ""
authors = ["Daniel Schweigert <dan.schweigert@gmail.com>"]
repository = "https://github.com/danielschweigert/clichessdrill"
license = "MIT"
include = [
    "LICENSE",
    "gameplans/default.json",
    "docs/screenshots/game_play_1.png",
    "docs/screenshots/game_play_2.png",
    "docs/screenshots/game_play_3.png",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-chess = "^1.999"
chess = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
clichessdrill="clichessdrill.main:main"