[tool.poetry]
name = "mypyliex"
version = "22.06.01-12"
description = "Project description"
authors = ["Tadeusz Miszczyk <tadeusz.miszczyk@bshg.com>"]
homepage = "http://github.com/8tm/my_python_library_example"
documentation = "https://test.pypi.org/project/my_python_library_example"
repository = "http://github.com/8tm/my_python_library_example"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: Unix",
]


[tool.poetry.dependencies]
python = "^3.8"
apischema = "^0.17.5"
jsonschema = "^4.4.0"
PyYAML = "^6.0"


[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-commas = "^2.0.0"
flake8-import-order = "^0.18.1"
flake8-quotes = "^3.2.0"
pytest = "^6.0.1"
pytest-cov = "^2.10.0"
pytest-mock = "^3.2.0"
pytest-random-order = "^1.0.4"
pytest-xdist = "^1.29.0"
pytest-parallel = "^0.1.1"
mypy = "^0.812"
pylint = "^2.5.0"


[tool.mypy]
ignore_missing_imports = true
warn_unused_configs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
strict_equality = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
