[project]
name = "cs.xml"
description = "A couple of trite XML conveniences: preferred `etree` import and a `pprint` function."
authors = [
    { name = "Cameron Simpson", email = "cs@cskk.id.au" },
]
keywords = [
    "python3",
]
dependencies = []
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
version = "20220606"

[project.license]
text = "GNU General Public License v3 or later (GPLv3+)"

[project.urls]
URL = "https://bitbucket.org/cameron_simpson/css/commits/all"

[project.readme]
text = """
A couple of trite XML conveniences:
preferred `etree` import and a `pprint` function.

*Latest release 20220606*:
Initial PyPI release.

## Function `pprint(xml, fp=None)`

Directly derived from the suggestion at:
http://stackoverflow.com/questions/749796/pretty-printing-xml-in-python

# Release Log



*Release 20220606*:
Initial PyPI release."""
content-type = "text/markdown"

[build-system]
requires = [
    "setuptools >= 61.0",
    "trove-classifiers",
    "wheel",
]
build-backend = "setuptools.build_meta"
