[tool.poetry]
name = "serval-config-utils"
packages = [
    {include = "configutils"}
]
version = "0.1.4"
description = "SerVal-Config-Utils automatically parse configurations from multiple sources into a single python dictionary."
authors = ["Thibault Simonetto <thibault.simonetto@uni.lu>"]
license = "MIT"
readme="README.md"

[tool.poetry.dependencies]
python = "^3.6.2"
PyYAML = ">=5.1, <7.0"
mergedeep = "^1.3.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"
pre-commit = "^2.16.0"
flake8 = "^4.0.1"
black = {version = "^21.12b0", allow-prereleases = true}
isort = "^5.10.1"
pip-licenses = "^3.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
