[build-system]
# Minimum requirements for the build system to execute.
requires = [
    'setuptools>=48.0',
    'wheel>=0.21',

    # Older numpy versions aren't fully compatible with Python's limited API
    'numpy==1.17.1; python_version=="3.7" and (platform_machine!="arm64" or platform_system!="Darwin") and platform_machine!="aarch64" and platform_machine!="loongarch64" and platform_system!="AIX" and platform_python_implementation != "PyPy"',
    'oldest-supported-numpy; python_version!="3.7" or (platform_machine=="arm64" and platform_system=="Darwin") or platform_machine=="aarch64" or platform_machine=="loongarch64" or platform_system=="AIX" or platform_python_implementation == "PyPy"',
]

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "scm.plams.*",
    "h5py.*",
    "scipy.*",
    "noodles.*",
    "schema.*",
    "mendeleev.*",
]
ignore_missing_imports = true

[tool.cibuildwheel]
build = [
    "cp37-manylinux_x86_64",
    "cp37-manylinux-aarch64",
    "cp37-macosx_x86_64",
]
build-verbosity = "3"
before-all = "cp licenses/LICENSE*.txt ."

[tool.cibuildwheel.linux]
environment = { QMFLOWS_INCLUDEDIR="", QMFLOWS_LIBDIR="", CFLAGS="-Werror", LDFLAGS="-Wl,--strip-debug" }
manylinux-x86_64-image = "ghcr.io/nlesc-nano/manylinux2014_x86_64-qmflows"
manylinux-aarch64-image = "ghcr.io/nlesc-nano/manylinux2014_aarch64-qmflows"
repair-wheel-command = "auditwheel -v repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
# TODO: Install CP2K for the tests once a workaround can be found for SCM-NV/qmflows#295
environment = { QMFLOWS_INCLUDEDIR="", QMFLOWS_LIBDIR="", LDFLAGS="-Wl", MACOSX_DEPLOYMENT_TARGET="10.14" }
repair-wheel-command = [
    "delocate-listdeps {wheel}",
    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}",
]
