[tool.poetry]
name = "yanpd"
version = "0.1.0"
description = "Yet Another Neo4j Python Driver"
authors = ["Denis <d.mulyalin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
yangson = "^1.4.13"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
bandit = "1.7.*"
black = "22.3.*"
flake8 = "4.0.*"
pre-commit = "2.15.*"
pyenchant = "3.2.*"
pylint = "2.12.*"
pytest = { version = "^7.1.*", markers = "python_version >= '3.7'" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
