name: Create Python release manylinux

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'py-v*' # Push events to matching py-v*, i.e. py-v1.0, py-v20.15.10
jobs:
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish x86_64
        uses: docker://konstin2/maturin:latest
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          entrypoint: /bin/bash
          args: .github/deploy_manylinux.sh
      # needed for docker on apple m1
      - name: publish aarch64
        uses: messense/maturin-action@main
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          rust-toolchain: stable
          manylinux: '2_17'
          target: aarch64-unknown-linux-gnu
          maturin-version: 0.12.7
          command: publish
          args: --no-sdist --skip-existing -o wheels -i python -u yankun
