# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import kubefox_pb2 as kubefox__pb2


class ComponentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallFunction = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/CallFunction',
                request_serializer=kubefox__pb2.KubeFoxData.SerializeToString,
                response_deserializer=kubefox__pb2.KubeFoxData.FromString,
                )
        self.GetTelemetry = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/GetTelemetry',
                request_serializer=kubefox__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=kubefox__pb2.TelemetryResponse.FromString,
                )


class ComponentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.CallFunction,
                    request_deserializer=kubefox__pb2.KubeFoxData.FromString,
                    response_serializer=kubefox__pb2.KubeFoxData.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=kubefox__pb2.TelemetryRequest.FromString,
                    response_serializer=kubefox__pb2.TelemetryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kubefox.proto.v1.ComponentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComponentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/CallFunction',
            kubefox__pb2.KubeFoxData.SerializeToString,
            kubefox__pb2.KubeFoxData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/GetTelemetry',
            kubefox__pb2.TelemetryRequest.SerializeToString,
            kubefox__pb2.TelemetryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
