"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.docker_environment_pb2
import layerapi.api.entity.source_code_environment_pb2
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class HyperparameterTuningMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class FixedParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        value: builtins.float
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: builtins.float = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    class Objective(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        METRIC_NAME_FIELD_NUMBER: builtins.int
        MAXIMIZE_FIELD_NUMBER: builtins.int
        metric_name: typing.Text
        maximize: builtins.bool
        def __init__(self,
            *,
            metric_name: typing.Text = ...,
            maximize: builtins.bool = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["maximize",b"maximize","metric_name",b"metric_name"]) -> None: ...

    class Environment(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SOURCE_CODE_ENV_FIELD_NUMBER: builtins.int
        DOCKER_ENV_FIELD_NUMBER: builtins.int
        @property
        def source_code_env(self) -> api.entity.source_code_environment_pb2.SourceCodeEnvironment: ...
        @property
        def docker_env(self) -> api.entity.docker_environment_pb2.DockerEnvironment: ...
        def __init__(self,
            *,
            source_code_env: typing.Optional[api.entity.source_code_environment_pb2.SourceCodeEnvironment] = ...,
            docker_env: typing.Optional[api.entity.docker_environment_pb2.DockerEnvironment] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["docker_env",b"docker_env","source_code_env",b"source_code_env","type",b"type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["docker_env",b"docker_env","source_code_env",b"source_code_env","type",b"type"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["type",b"type"]) -> typing.Optional[typing_extensions.Literal["source_code_env","docker_env"]]: ...

    class Strategy(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class _ParameterType:
            ValueType = typing.NewType('ValueType', builtins.int)
            V: typing_extensions.TypeAlias = ValueType
        class _ParameterTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HyperparameterTuningMetadata.Strategy._ParameterType.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            PARAMETER_TYPE_INVALID: HyperparameterTuningMetadata.Strategy._ParameterType.ValueType  # 0
            PARAMETER_TYPE_FLOAT: HyperparameterTuningMetadata.Strategy._ParameterType.ValueType  # 1
            PARAMETER_TYPE_INT: HyperparameterTuningMetadata.Strategy._ParameterType.ValueType  # 2
            PARAMETER_TYPE_STRING: HyperparameterTuningMetadata.Strategy._ParameterType.ValueType  # 3
        class ParameterType(_ParameterType, metaclass=_ParameterTypeEnumTypeWrapper):
            pass

        PARAMETER_TYPE_INVALID: HyperparameterTuningMetadata.Strategy.ParameterType.ValueType  # 0
        PARAMETER_TYPE_FLOAT: HyperparameterTuningMetadata.Strategy.ParameterType.ValueType  # 1
        PARAMETER_TYPE_INT: HyperparameterTuningMetadata.Strategy.ParameterType.ValueType  # 2
        PARAMETER_TYPE_STRING: HyperparameterTuningMetadata.Strategy.ParameterType.ValueType  # 3

        class ManualSearch(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class ParameterValues(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                class ParameterToValueEntry(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor
                    KEY_FIELD_NUMBER: builtins.int
                    VALUE_FIELD_NUMBER: builtins.int
                    key: typing.Text
                    @property
                    def value(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterInfo: ...
                    def __init__(self,
                        *,
                        key: typing.Text = ...,
                        value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterInfo] = ...,
                        ) -> None: ...
                    def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
                    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

                PARAMETER_TO_VALUE_FIELD_NUMBER: builtins.int
                @property
                def parameter_to_value(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___HyperparameterTuningMetadata.Strategy.ParameterInfo]: ...
                def __init__(self,
                    *,
                    parameter_to_value: typing.Optional[typing.Mapping[typing.Text, global___HyperparameterTuningMetadata.Strategy.ParameterInfo]] = ...,
                    ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["parameter_to_value",b"parameter_to_value"]) -> None: ...

            PARAMETER_VALUES_FIELD_NUMBER: builtins.int
            @property
            def parameter_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HyperparameterTuningMetadata.Strategy.ManualSearch.ParameterValues]: ...
            def __init__(self,
                *,
                parameter_values: typing.Optional[typing.Iterable[global___HyperparameterTuningMetadata.Strategy.ManualSearch.ParameterValues]] = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["parameter_values",b"parameter_values"]) -> None: ...

        class RandomSearch(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class ParametersEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: typing.Text
                @property
                def value(self) -> global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterRange: ...
                def __init__(self,
                    *,
                    key: typing.Text = ...,
                    value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterRange] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

            class ParametersCategoricalEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: typing.Text
                @property
                def value(self) -> global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterCategoricalRange: ...
                def __init__(self,
                    *,
                    key: typing.Text = ...,
                    value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterCategoricalRange] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

            class ParameterRange(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                TYPE_FIELD_NUMBER: builtins.int
                MIN_FIELD_NUMBER: builtins.int
                MAX_FIELD_NUMBER: builtins.int
                type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType
                @property
                def min(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                @property
                def max(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                def __init__(self,
                    *,
                    type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType = ...,
                    min: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    max: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min","type",b"type"]) -> None: ...

            class ParameterCategoricalRange(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                TYPE_FIELD_NUMBER: builtins.int
                VALUES_FIELD_NUMBER: builtins.int
                type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType
                @property
                def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HyperparameterTuningMetadata.Strategy.ParameterValue]: ...
                def __init__(self,
                    *,
                    type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType = ...,
                    values: typing.Optional[typing.Iterable[global___HyperparameterTuningMetadata.Strategy.ParameterValue]] = ...,
                    ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["type",b"type","values",b"values"]) -> None: ...

            PARAMETERS_FIELD_NUMBER: builtins.int
            PARAMETERS_CATEGORICAL_FIELD_NUMBER: builtins.int
            MAX_JOBS_FIELD_NUMBER: builtins.int
            @property
            def parameters(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterRange]: ...
            @property
            def parameters_categorical(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterCategoricalRange]: ...
            max_jobs: builtins.int
            def __init__(self,
                *,
                parameters: typing.Optional[typing.Mapping[typing.Text, global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterRange]] = ...,
                parameters_categorical: typing.Optional[typing.Mapping[typing.Text, global___HyperparameterTuningMetadata.Strategy.RandomSearch.ParameterCategoricalRange]] = ...,
                max_jobs: builtins.int = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["max_jobs",b"max_jobs","parameters",b"parameters","parameters_categorical",b"parameters_categorical"]) -> None: ...

        class GridSearch(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class ParametersEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: typing.Text
                @property
                def value(self) -> global___HyperparameterTuningMetadata.Strategy.GridSearch.ParameterRange: ...
                def __init__(self,
                    *,
                    key: typing.Text = ...,
                    value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.GridSearch.ParameterRange] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

            class ParameterRange(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                TYPE_FIELD_NUMBER: builtins.int
                MIN_FIELD_NUMBER: builtins.int
                MAX_FIELD_NUMBER: builtins.int
                STEP_FIELD_NUMBER: builtins.int
                type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType
                @property
                def min(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                @property
                def max(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                @property
                def step(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                def __init__(self,
                    *,
                    type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType = ...,
                    min: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    max: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    step: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min","step",b"step"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min","step",b"step","type",b"type"]) -> None: ...

            PARAMETERS_FIELD_NUMBER: builtins.int
            @property
            def parameters(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___HyperparameterTuningMetadata.Strategy.GridSearch.ParameterRange]: ...
            def __init__(self,
                *,
                parameters: typing.Optional[typing.Mapping[typing.Text, global___HyperparameterTuningMetadata.Strategy.GridSearch.ParameterRange]] = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["parameters",b"parameters"]) -> None: ...

        class BayesianSearch(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            class ParametersEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: typing.Text
                @property
                def value(self) -> global___HyperparameterTuningMetadata.Strategy.BayesianSearch.ParameterRange: ...
                def __init__(self,
                    *,
                    key: typing.Text = ...,
                    value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.BayesianSearch.ParameterRange] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

            class ParameterRange(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor
                TYPE_FIELD_NUMBER: builtins.int
                MIN_FIELD_NUMBER: builtins.int
                MAX_FIELD_NUMBER: builtins.int
                type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType
                @property
                def min(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                @property
                def max(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
                def __init__(self,
                    *,
                    type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType = ...,
                    min: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    max: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                    ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["max",b"max","min",b"min","type",b"type"]) -> None: ...

            PARAMETERS_FIELD_NUMBER: builtins.int
            MAX_JOBS_FIELD_NUMBER: builtins.int
            @property
            def parameters(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___HyperparameterTuningMetadata.Strategy.BayesianSearch.ParameterRange]: ...
            max_jobs: builtins.int
            def __init__(self,
                *,
                parameters: typing.Optional[typing.Mapping[typing.Text, global___HyperparameterTuningMetadata.Strategy.BayesianSearch.ParameterRange]] = ...,
                max_jobs: builtins.int = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["max_jobs",b"max_jobs","parameters",b"parameters"]) -> None: ...

        class ParameterInfo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            TYPE_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType
            @property
            def value(self) -> global___HyperparameterTuningMetadata.Strategy.ParameterValue: ...
            def __init__(self,
                *,
                type: global___HyperparameterTuningMetadata.Strategy.ParameterType.ValueType = ...,
                value: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ParameterValue] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["type",b"type","value",b"value"]) -> None: ...

        class ParameterValue(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            FLOAT_VALUE_FIELD_NUMBER: builtins.int
            INT_VALUE_FIELD_NUMBER: builtins.int
            STRING_VALUE_FIELD_NUMBER: builtins.int
            float_value: builtins.float
            int_value: builtins.int
            string_value: typing.Text
            def __init__(self,
                *,
                float_value: builtins.float = ...,
                int_value: builtins.int = ...,
                string_value: typing.Text = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["float_value",b"float_value","int_value",b"int_value","string_value",b"string_value","value",b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["float_value",b"float_value","int_value",b"int_value","string_value",b"string_value","value",b"value"]) -> None: ...
            def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["float_value","int_value","string_value"]]: ...

        MANUAL_SEARCH_FIELD_NUMBER: builtins.int
        RANDOM_SEARCH_FIELD_NUMBER: builtins.int
        GRID_SEARCH_FIELD_NUMBER: builtins.int
        BAYESIAN_SEARCH_FIELD_NUMBER: builtins.int
        @property
        def manual_search(self) -> global___HyperparameterTuningMetadata.Strategy.ManualSearch: ...
        @property
        def random_search(self) -> global___HyperparameterTuningMetadata.Strategy.RandomSearch: ...
        @property
        def grid_search(self) -> global___HyperparameterTuningMetadata.Strategy.GridSearch: ...
        @property
        def bayesian_search(self) -> global___HyperparameterTuningMetadata.Strategy.BayesianSearch: ...
        def __init__(self,
            *,
            manual_search: typing.Optional[global___HyperparameterTuningMetadata.Strategy.ManualSearch] = ...,
            random_search: typing.Optional[global___HyperparameterTuningMetadata.Strategy.RandomSearch] = ...,
            grid_search: typing.Optional[global___HyperparameterTuningMetadata.Strategy.GridSearch] = ...,
            bayesian_search: typing.Optional[global___HyperparameterTuningMetadata.Strategy.BayesianSearch] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["bayesian_search",b"bayesian_search","grid_search",b"grid_search","implementation",b"implementation","manual_search",b"manual_search","random_search",b"random_search"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["bayesian_search",b"bayesian_search","grid_search",b"grid_search","implementation",b"implementation","manual_search",b"manual_search","random_search",b"random_search"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["implementation",b"implementation"]) -> typing.Optional[typing_extensions.Literal["manual_search","random_search","grid_search","bayesian_search"]]: ...

    ENTRYPOINT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    MODEL_NAME_FIELD_NUMBER: builtins.int
    MODEL_VERSION_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    OBJECTIVE_FIELD_NUMBER: builtins.int
    FIXED_PARAMETERS_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    MAX_PARALLEL_JOBS_FIELD_NUMBER: builtins.int
    EARLY_STOP_FIELD_NUMBER: builtins.int
    FABRIC_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    entrypoint: typing.Text
    name: typing.Text
    description: typing.Text
    model_name: typing.Text
    model_version: typing.Text
    @property
    def environment(self) -> global___HyperparameterTuningMetadata.Environment: ...
    @property
    def objective(self) -> global___HyperparameterTuningMetadata.Objective: ...
    @property
    def fixed_parameters(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.float]: ...
    @property
    def strategy(self) -> global___HyperparameterTuningMetadata.Strategy: ...
    max_parallel_jobs: builtins.int
    early_stop: builtins.bool
    fabric: typing.Text
    @property
    def model_id(self) -> api.ids_pb2.ModelId: ...
    @property
    def project_id(self) -> api.ids_pb2.ProjectId: ...
    @property
    def organization_id(self) -> api.ids_pb2.OrganizationId: ...
    def __init__(self,
        *,
        entrypoint: typing.Text = ...,
        name: typing.Text = ...,
        description: typing.Text = ...,
        model_name: typing.Text = ...,
        model_version: typing.Text = ...,
        environment: typing.Optional[global___HyperparameterTuningMetadata.Environment] = ...,
        objective: typing.Optional[global___HyperparameterTuningMetadata.Objective] = ...,
        fixed_parameters: typing.Optional[typing.Mapping[typing.Text, builtins.float]] = ...,
        strategy: typing.Optional[global___HyperparameterTuningMetadata.Strategy] = ...,
        max_parallel_jobs: builtins.int = ...,
        early_stop: builtins.bool = ...,
        fabric: typing.Text = ...,
        model_id: typing.Optional[api.ids_pb2.ModelId] = ...,
        project_id: typing.Optional[api.ids_pb2.ProjectId] = ...,
        organization_id: typing.Optional[api.ids_pb2.OrganizationId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["environment",b"environment","model_id",b"model_id","objective",b"objective","organization_id",b"organization_id","project_id",b"project_id","strategy",b"strategy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","early_stop",b"early_stop","entrypoint",b"entrypoint","environment",b"environment","fabric",b"fabric","fixed_parameters",b"fixed_parameters","max_parallel_jobs",b"max_parallel_jobs","model_id",b"model_id","model_name",b"model_name","model_version",b"model_version","name",b"name","objective",b"objective","organization_id",b"organization_id","project_id",b"project_id","strategy",b"strategy"]) -> None: ...
global___HyperparameterTuningMetadata = HyperparameterTuningMetadata
