# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/billable_action_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$api/value/billable_action_type.proto\x12\x03\x61pi*|\n\x12\x42illableActionType\x12 \n\x1c\x42ILLABLE_ACTION_TYPE_INVALID\x10\x00\x12\"\n\x1e\x42ILLABLE_ACTION_TYPE_RESOURCES\x10\n\x12 \n\x1c\x42ILLABLE_ACTION_TYPE_FUNDING\x10\x0b\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')

_BILLABLEACTIONTYPE = DESCRIPTOR.enum_types_by_name['BillableActionType']
BillableActionType = enum_type_wrapper.EnumTypeWrapper(_BILLABLEACTIONTYPE)
BILLABLE_ACTION_TYPE_INVALID = 0
BILLABLE_ACTION_TYPE_RESOURCES = 10
BILLABLE_ACTION_TYPE_FUNDING = 11


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _BILLABLEACTIONTYPE._serialized_start=45
  _BILLABLEACTIONTYPE._serialized_end=169
# @@protoc_insertion_point(module_scope)
