[tool.poetry]
name = "rainbowlog"
version = "0.1.0"
description = "Format your python logs with colours based on the log levels."
authors = ["Abraham Murciano <abrahammurciano@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
ansicolors = "^1.1.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pdoc3 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
