[tool.poetry]
name = "steiner-tree"
version = "1.1.3"
description = "Steiner Tree algorithms"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
homepage = "https://github.com/binh-vu/steiner-tree"

[tool.poetry.dependencies]
python = "^3.6"
networkx = "^2.8.2"
graph-wrapper = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
