# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CommonModelResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'boundary_id': 'str',
        'created_date_time': 'datetime',
        'external_id': 'str',
        'id': 'str',
        'models': 'object',
        'modified_date_time': 'datetime',
        'org_id': 'str',
        'properties': 'object',
        'status': 'str',
        'tenant_type': 'str'
    }

    attribute_map = {
        'boundary_id': 'boundaryId',
        'created_date_time': 'createdDateTime',
        'external_id': 'externalId',
        'id': 'id',
        'models': 'models',
        'modified_date_time': 'modifiedDateTime',
        'org_id': 'orgId',
        'properties': 'properties',
        'status': 'status',
        'tenant_type': 'tenantType'
    }

    def __init__(self, boundary_id=None, created_date_time=None, external_id=None, id=None, models=None, modified_date_time=None, org_id=None, properties=None, status=None, tenant_type=None, _configuration=None):  # noqa: E501
        """CommonModelResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._boundary_id = None
        self._created_date_time = None
        self._external_id = None
        self._id = None
        self._models = None
        self._modified_date_time = None
        self._org_id = None
        self._properties = None
        self._status = None
        self._tenant_type = None
        self.discriminator = None

        if boundary_id is not None:
            self.boundary_id = boundary_id
        if created_date_time is not None:
            self.created_date_time = created_date_time
        if external_id is not None:
            self.external_id = external_id
        if id is not None:
            self.id = id
        if models is not None:
            self.models = models
        if modified_date_time is not None:
            self.modified_date_time = modified_date_time
        if org_id is not None:
            self.org_id = org_id
        if properties is not None:
            self.properties = properties
        if status is not None:
            self.status = status
        if tenant_type is not None:
            self.tenant_type = tenant_type

    @property
    def boundary_id(self):
        """Gets the boundary_id of this CommonModelResponse.  # noqa: E501


        :return: The boundary_id of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._boundary_id

    @boundary_id.setter
    def boundary_id(self, boundary_id):
        """Sets the boundary_id of this CommonModelResponse.


        :param boundary_id: The boundary_id of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._boundary_id = boundary_id

    @property
    def created_date_time(self):
        """Gets the created_date_time of this CommonModelResponse.  # noqa: E501


        :return: The created_date_time of this CommonModelResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time):
        """Sets the created_date_time of this CommonModelResponse.


        :param created_date_time: The created_date_time of this CommonModelResponse.  # noqa: E501
        :type: datetime
        """

        self._created_date_time = created_date_time

    @property
    def external_id(self):
        """Gets the external_id of this CommonModelResponse.  # noqa: E501


        :return: The external_id of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this CommonModelResponse.


        :param external_id: The external_id of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def id(self):
        """Gets the id of this CommonModelResponse.  # noqa: E501


        :return: The id of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CommonModelResponse.


        :param id: The id of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def models(self):
        """Gets the models of this CommonModelResponse.  # noqa: E501


        :return: The models of this CommonModelResponse.  # noqa: E501
        :rtype: object
        """
        return self._models

    @models.setter
    def models(self, models):
        """Sets the models of this CommonModelResponse.


        :param models: The models of this CommonModelResponse.  # noqa: E501
        :type: object
        """

        self._models = models

    @property
    def modified_date_time(self):
        """Gets the modified_date_time of this CommonModelResponse.  # noqa: E501


        :return: The modified_date_time of this CommonModelResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_date_time

    @modified_date_time.setter
    def modified_date_time(self, modified_date_time):
        """Sets the modified_date_time of this CommonModelResponse.


        :param modified_date_time: The modified_date_time of this CommonModelResponse.  # noqa: E501
        :type: datetime
        """

        self._modified_date_time = modified_date_time

    @property
    def org_id(self):
        """Gets the org_id of this CommonModelResponse.  # noqa: E501


        :return: The org_id of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this CommonModelResponse.


        :param org_id: The org_id of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def properties(self):
        """Gets the properties of this CommonModelResponse.  # noqa: E501


        :return: The properties of this CommonModelResponse.  # noqa: E501
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this CommonModelResponse.


        :param properties: The properties of this CommonModelResponse.  # noqa: E501
        :type: object
        """

        self._properties = properties

    @property
    def status(self):
        """Gets the status of this CommonModelResponse.  # noqa: E501


        :return: The status of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CommonModelResponse.


        :param status: The status of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tenant_type(self):
        """Gets the tenant_type of this CommonModelResponse.  # noqa: E501


        :return: The tenant_type of this CommonModelResponse.  # noqa: E501
        :rtype: str
        """
        return self._tenant_type

    @tenant_type.setter
    def tenant_type(self, tenant_type):
        """Sets the tenant_type of this CommonModelResponse.


        :param tenant_type: The tenant_type of this CommonModelResponse.  # noqa: E501
        :type: str
        """

        self._tenant_type = tenant_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CommonModelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CommonModelResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CommonModelResponse):
            return True

        return self.to_dict() != other.to_dict()
