# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PlotUploadHistoryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'message': 'str',
        'plot_count': 'int',
        'plot_details': 'list[PlotDetails]',
        'properties': 'object',
        'ref_no': 'str',
        'status': 'str',
        'upload_status': 'bool',
        'upload_type': 'str'
    }

    attribute_map = {
        'file_name': 'fileName',
        'message': 'message',
        'plot_count': 'plotCount',
        'plot_details': 'plotDetails',
        'properties': 'properties',
        'ref_no': 'refNo',
        'status': 'status',
        'upload_status': 'uploadStatus',
        'upload_type': 'uploadType'
    }

    def __init__(self, file_name=None, message=None, plot_count=None, plot_details=None, properties=None, ref_no=None, status=None, upload_status=None, upload_type=None, _configuration=None):  # noqa: E501
        """PlotUploadHistoryRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file_name = None
        self._message = None
        self._plot_count = None
        self._plot_details = None
        self._properties = None
        self._ref_no = None
        self._status = None
        self._upload_status = None
        self._upload_type = None
        self.discriminator = None

        if file_name is not None:
            self.file_name = file_name
        if message is not None:
            self.message = message
        if plot_count is not None:
            self.plot_count = plot_count
        if plot_details is not None:
            self.plot_details = plot_details
        if properties is not None:
            self.properties = properties
        if ref_no is not None:
            self.ref_no = ref_no
        if status is not None:
            self.status = status
        if upload_status is not None:
            self.upload_status = upload_status
        if upload_type is not None:
            self.upload_type = upload_type

    @property
    def file_name(self):
        """Gets the file_name of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The file_name of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this PlotUploadHistoryRequest.


        :param file_name: The file_name of this PlotUploadHistoryRequest.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def message(self):
        """Gets the message of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The message of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this PlotUploadHistoryRequest.


        :param message: The message of this PlotUploadHistoryRequest.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def plot_count(self):
        """Gets the plot_count of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The plot_count of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: int
        """
        return self._plot_count

    @plot_count.setter
    def plot_count(self, plot_count):
        """Sets the plot_count of this PlotUploadHistoryRequest.


        :param plot_count: The plot_count of this PlotUploadHistoryRequest.  # noqa: E501
        :type: int
        """

        self._plot_count = plot_count

    @property
    def plot_details(self):
        """Gets the plot_details of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The plot_details of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: list[PlotDetails]
        """
        return self._plot_details

    @plot_details.setter
    def plot_details(self, plot_details):
        """Sets the plot_details of this PlotUploadHistoryRequest.


        :param plot_details: The plot_details of this PlotUploadHistoryRequest.  # noqa: E501
        :type: list[PlotDetails]
        """

        self._plot_details = plot_details

    @property
    def properties(self):
        """Gets the properties of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The properties of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this PlotUploadHistoryRequest.


        :param properties: The properties of this PlotUploadHistoryRequest.  # noqa: E501
        :type: object
        """

        self._properties = properties

    @property
    def ref_no(self):
        """Gets the ref_no of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The ref_no of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._ref_no

    @ref_no.setter
    def ref_no(self, ref_no):
        """Sets the ref_no of this PlotUploadHistoryRequest.


        :param ref_no: The ref_no of this PlotUploadHistoryRequest.  # noqa: E501
        :type: str
        """

        self._ref_no = ref_no

    @property
    def status(self):
        """Gets the status of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The status of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PlotUploadHistoryRequest.


        :param status: The status of this PlotUploadHistoryRequest.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def upload_status(self):
        """Gets the upload_status of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The upload_status of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._upload_status

    @upload_status.setter
    def upload_status(self, upload_status):
        """Sets the upload_status of this PlotUploadHistoryRequest.


        :param upload_status: The upload_status of this PlotUploadHistoryRequest.  # noqa: E501
        :type: bool
        """

        self._upload_status = upload_status

    @property
    def upload_type(self):
        """Gets the upload_type of this PlotUploadHistoryRequest.  # noqa: E501


        :return: The upload_type of this PlotUploadHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._upload_type

    @upload_type.setter
    def upload_type(self, upload_type):
        """Sets the upload_type of this PlotUploadHistoryRequest.


        :param upload_type: The upload_type of this PlotUploadHistoryRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["BOUNDARY_FILE", "BULK_UPLOAD", "DRAW_ON_MAP", "SURVEY"]  # noqa: E501
        if (self._configuration.client_side_validation and
                upload_type not in allowed_values):
            raise ValueError(
                "Invalid value for `upload_type` ({0}), must be one of {1}"  # noqa: E501
                .format(upload_type, allowed_values)
            )

        self._upload_type = upload_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlotUploadHistoryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlotUploadHistoryRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PlotUploadHistoryRequest):
            return True

        return self.to_dict() != other.to_dict()
