[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Denis Rosset <physics@denisrosset.com>"]
description = "Brent's algorithm"
license = "MIT"
name = "pydagogy-brent"
readme = "README.md"
repository = "https://github.com/denisrosset/brent-level-2.git"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^12.0.0" 

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
pylint = "^2.13.4"


[tool.black]
line-length = 99
target_version = ['py38']

[tool.isort]
line_length = 99
profile = "black"
py_version = 38

[tool.pytest.ini_options]
addopts = [
  "--tb=short",
  "--doctest-modules",
]

doctest_optionflags = ['NORMALIZE_WHITESPACE', 'IGNORE_EXCEPTION_DETAIL', 'ELLIPSIS', 'NUMBER']

testpaths = [
  "src/pydagogy_brent",
  "tests",
]
