[tool.poetry]
name = "declarative_argparse"
version = "0.0.1"
description = "A simple wrapper around argparse to permit declarative construction and argument retrieval."
authors = ["Rob Nelson <nexisentertainment@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.960"
autopep8 = "^1.6.0"
isort = "^5.10.1"
poetryup = "^0.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
