[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
# Description
name = "jupyterauth-neptune"
version = "0.2"
description = "Custom JupyterHub authenticator for the Neptune platform."
# Credentials
license = "MIT"
authors = ["Noos Energy <contact@noos.energy>"]
homepage = "https://github.com/noosenergy/jupyterauth-neptune"
# Package data
readme = "README.md"
packages = [
    { include = "jupyterauth_neptune", from = "src" },
]
# Distribution
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8"
jupyterhub = ">=0.8"
noos-pyk = "*"
tornado = "*"
traitlets = "*"

[tool.poetry.dev-dependencies]
# Format
black = "*"
isort = "*"
# Linter
pydocstyle = "*"
flake8 = "*"
mypy = "*"
# Testing
pytest = "*"
pytest-mock = "*"
pytest-asyncio = "*"
# Debugging
ipdb = "*"
ipython = "*"

[tool.black]
line-length = 99
target_version = ['py38']

[tool.isort]
line_length = 99
profile = "black"
multi_line_output = 3
lines_after_imports = 2
default_section = "THIRDPARTY"
known_first_party = "noos_pyk,jupyterauth_neptune,tests"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
install_types = true
non_interactive = true
incremental = true
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
warn_redundant_casts = true
ignore_missing_imports = true

[tool.pytest.ini_options]
python_files = "test_*.py"
python_classes = "Test"
python_functions = "test_*"
junit_family = "xunit2"
filterwarnings = "error::RuntimeWarning"
addopts = "--junitxml=pytest.xml"
