[tool.poetry]
name = "redis-pal"
version = "1.0.0"
description = "Store things in Redis without worrying about types or anything, just do it!"
authors = ["Gabriel Gazola Milan <gabriel.gazola@poli.ufrj.br>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
dill = "^0.3.5"
redis = "^4.0"

[tool.poetry.dev-dependencies]
numpy = "^1.22.4"
pytest-cov = "^3.0.0"
codecov = "^2.1.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
