[tool.poetry]
name = "tardis-ingestors"
version = "0.4.4"
description = "Tardis.dev ingestors for processed data"
authors = ["miguel-bm <miguel.blanco.marcos@gmail.com>"]
license = "MIT"
packages = [
    { include = "tardis" }
]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "1.3.4"
tardis-dev = "^2.0.0-alpha.10"
typedframe = "^0.6.2"
pydantic = "^1.9.0"
requests = "^2.27.1"
python-dotenv = "^0.20.0"
py_vollib = "^1.0.1"
SQLAlchemy = "^1.4.36"
pg8000 = "^1.26.1"
dask = {version = "2020.12.0", extras = ["dataframe"]}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
