[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
exclude = [
  ".*",
  "dist",
  "docs",
  "docsbuild",
  "htmlcov",
  "scripts",
  "tests",
  "*__pycache__*",
  "*.pyc"
]
name = "switchbee"
version = "1.1.0"
description = "SwitchBee Python integration."
license = "Apache-2.0"
authors = [ "Jafar Atili <at.jafar@outlook.com>" ]
readme = "README.md"
