[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygav"
version = "0.0.0"
description = "Useful stuff"
readme = "README.md"
authors = [{ name = "Nikos Gavalas", email = "ngavalas@protonmail.com" }]
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
]
keywords = ["utilities"]
dependencies = []
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]

[project.urls]
Homepage = "https://github.com/nikosgavalas/pygav"

#[project.scripts]
#mycli = "utilities.__main__:main"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
