[tool.poetry]
name = "yet_another_simple_rss_parser"
version = "0.0.5"
description = "Simple RSS reader/parser"
authors = ["Barak Bloch <barak.bloch@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://www.pypi.org/project/yet-another-simple-rss-parser/"
repository = "https://github.com/barakbl/simple_rss_reader"
keywords = ["rss", "parser"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

include = [
    "LICENSE",
]

packages = [
    { include = "simple_rss_reader" }
]





[tool.poetry.dependencies]
# Updated Python version
python = "^3.6"
# New dependency
flake8 = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

# New scripts
# [tool.poetry.scripts]
#lake8-markdown = 'flake8_markdown:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
