
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-03T10:13:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd61ea19428a6d4cf4d2beb17bd2e80ed4995990",
 "version": "0.1.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
