[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "SAPL-Flask"
version = "0.0.2"
description = "initial upload to register the name for future development"
readme = "README.md"
authors = [{ name = "Dominic Heutelbeck", email = "dominic@heutelbeck.com"}]
license = { file = "LICENSE" }


[tools.setuptools]
packages = ["sapl_flask"]