version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

formats:
    - epub
    - htmlzip
    - pdf

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true
