[tool.poetry]
name = "fdce"
version = "0.1.1-alpha.0"
description = "Finite difference coefficients estimator"
authors = ["Jorge Morgado Vega <jorge.morgadov@gmail.com>"]
license = "MIT"
include = [
    { path = "fdce/_extension/*.so", format = "wheel" }
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.0"

[tool.poetry.dev-dependencies]
pylint = "^2.14.0"
black = "^22.3.0"
isort = "^5.10.1"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
