from hw1lib.curry_class import AUDUSD_return
from hw1lib.curry_class import GBPEUR_return
from hw1lib.curry_class import USDCAD_return
from hw1lib.curry_class import USDJPY_return
from hw1lib.curry_class import USDMXN_return
from hw1lib.curry_class import EURUSD_return
from hw1lib.curry_class import USDCNY_return
from hw1lib.curry_class import USDCZK_return
from hw1lib.curry_class import USDPLN_return
from hw1lib.curry_class import USDINR_return