[tool.poetry]
name = "AlekSIS"
version = "2021.12.1.dev0"
packages = [ { include = "aleksis_meta" } ]
include = ["LICNECE.rst"]
readme = "README.rst"

description = "Free School Information System Distribution"
authors = ["Dominik George <dominik.george@teckids.org>"]
maintainers = ["Jonathan Weth <wethjo@katharineum.de>", "Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://aleksis.org/"
repository = "https://edugit.org/AlekSIS/official/AlekSIS"
keywords = ["SIS", "education", "school", "digitisation", "school apps"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Topic :: Education",
]

[tool.poetry.dependencies]
aleksis-core = { version = "~2.7", extras = ["ldap", "s3", "sentry"]}
aleksis-app-alsijil = "~2.0"
aleksis-app-chronos = "~2.2"
aleksis-app-csvimport = "~2.2"
aleksis-app-dashboardfeeds = "~2.0"
aleksis-app-hjelp = "~2.0"
aleksis-app-ldap = "~2.1"
aleksis-app-resint = "~2.1"
aleksis-app-untis = "~2.1"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
