
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T03:24:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "df9b5635e656352e5f78eca0693ac87de71eab66",
 "version": "1.16.0.post.dev640"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
