[tool.poetry]
name = "purplepipes"
version = "0.1.0"
description = "Pipes for data processing using pandas."
authors = ["J 'Indi' Harrington <indigoharrington@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/SentientHousePlant/purplepipes"
repository = "https://github.com/SentientHousePlant/purplepipes"
keywords = ["pandas", "data", "processes"]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
pre-commit = "^2.19.0"
coverage = "^6.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
