
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-05T22:38:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8937853a3e8b74d27eb4a7d47a1b82328804911d",
 "version": "7.1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
