# pyproject.toml

[build-system]
requires      = ["setuptools>=62.3.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python_ufile"
version = "1.0.10"
description = "Upload/Download from ufile.io as a guest or with an API Key."
readme = "README.md"
authors = [{ name = "Aria Bagheri", email = "ariab9342@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["python", "ufile", "ufile.io", "download", "upload", "anonymous"]
dependencies = [
    "aiofiles>=0.8.0",
    "asyncio>=3.4.3",
    "requests>=2.27.1"
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/AriaBagheri/python_ufile"

[tool.bumpver]
current_version = "1.0.10"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"src/ufile/__init__.py" = ["{version}"]
