[tool.poetry]
name = "usergen"
version = "0.1.3"
description = "A simple cli package to make requests on randomuser api."
authors = ["João Nogueira <joaopcnogueira@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
