[tool.poetry]
name = "file-merger"
version = "0.1.0rc1"
description = "Merge multiple text files into one"
authors = ["Ilia <istudyatuni@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
file-merger = "file_merger:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
