[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "cortex_airflow_lib"
description = "cortex airflow SDK"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'awswrangler>=2.11.0,<2.14.0',
    'pyarrow>=4.0.1,<5.1.0',
    'python_version>="3.7"',
]
dynamic = ["version"]

