[tool.poetry]
name = "cfdi_to_xml"
version = "0.0.4"
description = "Library to create XML fiel from CFDI representation."
authors = ["Moises Navarro <moisalejandro@gmail.com>"]
license = "LGPL-2.1"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
xsdata = "^22.4"
requests = "^2.27.1"
lxml = "^4.8.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
coverage = "^6.3.1"
isort = "^5.10.1"
mypy = "^0.931"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
hypothesis = "^6.36.1"
types-pyOpenSSL = "^22.0.0"
pylint = "^2.12.2"
pre-commit = "^2.17.0"
xsdata = {extras = ["cli"], version = "^22.4"}
types-requests = "^2.27.24"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.pylint.messages]
disable = "missing-function-docstring, missing-module-docstring, missing-class-docstring, fixme, duplicate-code, line-too-long, too-many-lines, too-many-instance-attributes, too-few-public-methods"

[tool.isort]
sections = "FUTURE, STDLIB, THIRDPARTY, FIRSTPARTY, LOCALFOLDER"
default_section = "THIRDPARTY"

[tool.pytest.ini_options]
pythonpath = "src/"
