[tool.poetry]
name = "file-merger"
version = "0.1.0rc2"
description = "Merge multiple text files into one"
authors = ["Ilia <istudyatuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/istudyatuni/file-merger"

[tool.poetry.urls]
"Tracker" = "https://github.com/istudyatuni/file-merger/issues"

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
file-merger = "file_merger:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
