[tool.poetry]
name = "codeobfuscate"
version = "1.0.1"
description = ""
authors = ["Hawchik"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
