[tool.poetry]
name = "woodie"
version = "0.0.2"
description = ""
authors = ["limonyellow"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/limonyellow/woodie"


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
