
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T21:01:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0933e586e7defca2d6e53169a4b5a493d26cdba4",
 "version": "2022.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
