[build-system]
requires = ["setuptools>=43", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-ava"
version = "0.1.2"
description = "Automated Vehicle Architecture"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Jiri Vlasak"}
]

[project.urls]
repository = "https://git.sr.ht/~qeef/py-ava"
documentation = "https://py-ava.readthedocs.io"
changelog = "https://git.sr.ht/~qeef/py-ava/refs"
