[tool.poetry]
name = "barim"
version = "0.1.1"
description = "Barim is a Python library that helps building CLI applications"
authors = ["Candotti Luca <candotti.luca@outlook.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.dependencies]
python = ">=3.7, <4.0"

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = "^22.1.0"
coverage = "^6.3.2"
isort = "^5.10.1"
mypy = "^0.941"
pytest = "^7.0.1"
sphinx = "^4.4.0"
sphinxawesome-theme = "^3.3.0"
tox = "^3.25.0"

[tool.black]
line-length = 120

[tool.isort]
src_paths = ["barim"]
profile = "black"
line_length = 120
dedup_headings = true
combine_as_imports = true
only_modified = true
verbose = true

[tool.mypy]
allow_redefinition = true
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["*.tests.*"]
ignore_errors = true

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37, py38, py39, py310

[testenv]
deps = pytest
commands = pytest --junitxml=reports/report.tox-{basepython}.xml
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
