[tool.poetry]
name = "append-hygiene-sdk"
version = "0.1.0"
description = ""
authors = ["TheBridgeDan <97176881+TheBridgeDan@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "append_hygiene_sdk" }]
homepage = "https://github.com/oneaudience/data-team-append-hygiene-sdk"
repository = "https://github.com/oneaudience/data-team-append-hygiene-sdk"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.20.0"
requests = "^2.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
