# coding: utf-8

"""
    Collibra Catalog API

    The Catalog API offers functionality related to the catalog product.<br/>It is mainly focused on facilitating the ingestion of information into Catalog. The API enables users to more easily connect Catalog to sources that are not necessarily natively supported in the product.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import collibra_catalog
from collibra_catalog.models.job_server_instance_response import JobServerInstanceResponse  # noqa: E501
from collibra_catalog.rest import ApiException

class TestJobServerInstanceResponse(unittest.TestCase):
    """JobServerInstanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobServerInstanceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = collibra_catalog.models.job_server_instance_response.JobServerInstanceResponse()  # noqa: E501
        if include_optional :
            return JobServerInstanceResponse(
                total = 1000, 
                offset = 10, 
                limit = 100, 
                results = [
                    collibra_catalog.models.job_server_instance.JobServerInstance(
                        id = '0', 
                        name = '0', 
                        address = '0', )
                    ]
            )
        else :
            return JobServerInstanceResponse(
        )

    def testJobServerInstanceResponse(self):
        """Test JobServerInstanceResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
