[tool.poetry]
name = "eciespy"
packages = [
  {include = "ecies"},
]
version = "0.3.12"
# docs
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
description = "Elliptic Curve Integrated Encryption Scheme for secp256k1 in Python"
license = "MIT"
maintainers = ["Weiliang Li <to.be.impressive@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ecies/py"
# tags
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: Implementation :: CPython",
  "Operating System :: OS Independent",
  "Topic :: Security :: Cryptography",
]
keywords = [
  "secp256k1",
  "crypto",
  "elliptic curves",
  "ecies",
  "bitcoin",
  "ethereum",
  "cryptocurrency",
]
# package data
include = ["ecies/py.typed"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"

# 3rd party
coincurve = ">=13,<18"
eth-keys = "^0.4.0"
pycryptodome = "^3.14.1"

[tool.poetry.dev-dependencies]
black = "^22.3"
flake8 = "^4.0.1"
ipython = {version = "^8.3.0", python = "^3.8"}
mypy = "^0.960"

[tool.poetry.scripts]
eciespy = "ecies.__main__:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
