
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T18:35:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8eb96dfb0ffdebb099a47a77d2b4653988b4a0b8",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
