[tool.poetry]
name = "mocking"
version = "0.0.0-b0"
description = ""
authors = ["Daniel Knell <contact@danielknell.co.uk>"]
readme = "README.md"
packages = [{include = "mocking", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pylint = "^2.12.2"
black = "^22.1.0"
isort = "^5.10.1"
mypy = "^0.941"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.SIMILARITIES]
ignore-signatures=true