"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import serviceb_client
from serviceb_client.api.genres_api import GenresApi  # noqa: E501


class TestGenresApi(unittest.TestCase):
    """GenresApi unit test stubs"""

    def setUp(self):
        self.api = GenresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_genres_genres_get(self):
        """Test case for get_genres_genres_get

        Get Genres  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
