# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubefox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkubefox.proto\x12\x10kubefox.proto.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe6\x02\n\x0bKubeFoxData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x39\n\x06labels\x18\x02 \x03(\x0b\x32).kubefox.proto.v1.KubeFoxData.LabelsEntry\x12\x39\n\x06\x63laims\x18\x03 \x03(\x0b\x32).kubefox.proto.v1.KubeFoxData.ClaimsEntry\x12%\n\x04\x61rgs\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06values\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x14\n\x0c\x63ontent_type\x18\x0e \x01(\t\x12\x0f\n\x07\x63ontent\x18\x0f \x01(\x0c\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0b\x43laimsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x12\n\x10TelemetryRequest\"$\n\x11TelemetryResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\xb9\x01\n\x10\x43omponentService\x12L\n\x0c\x43\x61llFunction\x12\x1d.kubefox.proto.v1.KubeFoxData\x1a\x1d.kubefox.proto.v1.KubeFoxData\x12W\n\x0cGetTelemetry\x12\".kubefox.proto.v1.TelemetryRequest\x1a#.kubefox.proto.v1.TelemetryResponseB\x18Z\x16github.com/kubefox/sdkb\x06proto3')



_KUBEFOXDATA = DESCRIPTOR.message_types_by_name['KubeFoxData']
_KUBEFOXDATA_LABELSENTRY = _KUBEFOXDATA.nested_types_by_name['LabelsEntry']
_KUBEFOXDATA_CLAIMSENTRY = _KUBEFOXDATA.nested_types_by_name['ClaimsEntry']
_TELEMETRYREQUEST = DESCRIPTOR.message_types_by_name['TelemetryRequest']
_TELEMETRYRESPONSE = DESCRIPTOR.message_types_by_name['TelemetryResponse']
KubeFoxData = _reflection.GeneratedProtocolMessageType('KubeFoxData', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _KUBEFOXDATA_LABELSENTRY,
    '__module__' : 'kubefox_pb2'
    # @@protoc_insertion_point(class_scope:kubefox.proto.v1.KubeFoxData.LabelsEntry)
    })
  ,

  'ClaimsEntry' : _reflection.GeneratedProtocolMessageType('ClaimsEntry', (_message.Message,), {
    'DESCRIPTOR' : _KUBEFOXDATA_CLAIMSENTRY,
    '__module__' : 'kubefox_pb2'
    # @@protoc_insertion_point(class_scope:kubefox.proto.v1.KubeFoxData.ClaimsEntry)
    })
  ,
  'DESCRIPTOR' : _KUBEFOXDATA,
  '__module__' : 'kubefox_pb2'
  # @@protoc_insertion_point(class_scope:kubefox.proto.v1.KubeFoxData)
  })
_sym_db.RegisterMessage(KubeFoxData)
_sym_db.RegisterMessage(KubeFoxData.LabelsEntry)
_sym_db.RegisterMessage(KubeFoxData.ClaimsEntry)

TelemetryRequest = _reflection.GeneratedProtocolMessageType('TelemetryRequest', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYREQUEST,
  '__module__' : 'kubefox_pb2'
  # @@protoc_insertion_point(class_scope:kubefox.proto.v1.TelemetryRequest)
  })
_sym_db.RegisterMessage(TelemetryRequest)

TelemetryResponse = _reflection.GeneratedProtocolMessageType('TelemetryResponse', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYRESPONSE,
  '__module__' : 'kubefox_pb2'
  # @@protoc_insertion_point(class_scope:kubefox.proto.v1.TelemetryResponse)
  })
_sym_db.RegisterMessage(TelemetryResponse)

_COMPONENTSERVICE = DESCRIPTOR.services_by_name['ComponentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026github.com/kubefox/sdk'
  _KUBEFOXDATA_LABELSENTRY._options = None
  _KUBEFOXDATA_LABELSENTRY._serialized_options = b'8\001'
  _KUBEFOXDATA_CLAIMSENTRY._options = None
  _KUBEFOXDATA_CLAIMSENTRY._serialized_options = b'8\001'
  _KUBEFOXDATA._serialized_start=66
  _KUBEFOXDATA._serialized_end=424
  _KUBEFOXDATA_LABELSENTRY._serialized_start=332
  _KUBEFOXDATA_LABELSENTRY._serialized_end=377
  _KUBEFOXDATA_CLAIMSENTRY._serialized_start=379
  _KUBEFOXDATA_CLAIMSENTRY._serialized_end=424
  _TELEMETRYREQUEST._serialized_start=426
  _TELEMETRYREQUEST._serialized_end=444
  _TELEMETRYRESPONSE._serialized_start=446
  _TELEMETRYRESPONSE._serialized_end=482
  _COMPONENTSERVICE._serialized_start=485
  _COMPONENTSERVICE._serialized_end=670
# @@protoc_insertion_point(module_scope)
