
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T15:06:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "31413d78aa853a3134f2034ba1ab240b54fa7218",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
