[build-dependencies]
dunce = "1"
prost-build = "0.10"
walkdir = "2"
[dependencies.pyo3]
features = ["extension-module"]
version = "0.15.1"

[dependencies.substrait-validator]
path = "local_dependencies/substrait-validator"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]
doc = false
name = "substrait_validator"

[package]
edition = "2018"
include = ["/LICENSE", "/README.md", "/build.rs", "/pyproject.toml", "/proto", "/text", "/src", "/substrait_validator/*.py", "/substrait_validator_build/*.py", "/tests"]
license = "Apache-2.0"
name = "substrait-validator-py"
version = "0.0.1"
