[build-dependencies]
prost-build = "0.10"
walkdir = "2"

[dependencies]
base64 = "0.13"
chrono = "0.4"
float-pretty-print = "0.1"
glob = "0.3"
heck = "0.4"
itertools = "0.8"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.9"
percent-encoding = "2.1"
prost = "0.10"
prost-types = "0.10"
regex = "1.5"
serde_json = "1"
strum = "0.23"
strum_macros = "0.23"
thiserror = "1.0"
uriparse = "0.6"
url = "2.2"
yaml-rust = "0.4"

[dependencies.curl]
optional = true
version = "0.4"

[dependencies.jsonschema]
default-features = false
version = "=0.15.0"

[dependencies.substrait-validator-derive]
path = "../substrait-validator-derive"
version = "0.0.1"

[features]
private_docs = []

[package]
description = "Substrait validator"
edition = "2021"
homepage = "https://substrait.io/"
include = ["src", "build.rs", "README.md"]
license = "Apache-2.0"
name = "substrait-validator"
readme = "README.md"
repository = "https://github.com/substrait-io/substrait"
version = "0.0.1"
