
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-01T13:38:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a679d51ccff9d3a8fec978b5acfc4e650cdd18f2",
 "version": "2.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
