default_language_version:
  python: python3.9
exclude: "venv"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language: python_venv
        additional_dependencies: ["flake8-comprehensions"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        exclude: ^tests/

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0 # or master if you're bold
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=100]
