
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T15:20:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aad96847a644c6bb18670ef364ecbceb8ca7b39b",
 "version": "0.7.1.post.dev586"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
