[tool.poetry]
name = "importlib-metadata-argparse-version"
version = "0.1.0"
description = "Argparse action to define CLI version with a delayed call to importlib.metadata"
readme = "README.md"
authors = ["Álvaro Mondéjar Rubio <mondejar1994@gmail.com>"]
license = "BSD-3-License"
repository = "https://github.com/mondeja/importlib-metadata-argparse-version"
documentation = "https://github.com/mondeja/importlib-metadata-argparse-version#usage"
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
]
packages = [{include = "importlib_metadata_argparse_version.py"}]

[tool.poetry.urls]
"Bug tracker" = "https://github.com/mondeja/importlib-metadata-argparse-version/issues"

[tool.poetry.dependencies]
python = "^3.7"
importlib_metadata = { version = "*", python = "<3.8" }

[tool.poetry.group.test.dependencies]
pytest = "^7"
