
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-03T20:40:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b2d1063b3d6d992f7d5d6b07cbdb04019169c89",
 "version": "0.2.4.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
