# Generated by Django 3.2.3 on 2021-12-27 10:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0006_auto_20211003_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommenu',
            name='stream',
            field=wagtail.core.fields.StreamField([('containers', wagtail.core.blocks.StructBlock([('stream', wagtail.core.blocks.StreamBlock([('container', wagtail.core.blocks.StructBlock([('stream', wagtail.core.blocks.StreamBlock([('linkblock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the link', max_length=50, required=True)), ('page', wagtail.core.blocks.PageChooserBlock(label='A page to be opened')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))])), ('linkcategory', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the category', max_length=50, required=True)), ('stream', wagtail.core.blocks.StreamBlock([('linkblock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the link', max_length=50, required=True)), ('page', wagtail.core.blocks.PageChooserBlock(label='A page to be opened')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))])), ('categorychildren', wagtail.core.blocks.StructBlock([('parent', wagtail.core.blocks.PageChooserBlock(label='A page which children should be listed'))]))], label='A nested content of a category')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))]))], label='Content of Column'))], icon='doc-full', label='Column'))], label='Columns'))], icon='container', label='More Columns')), ('linkblock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the link', max_length=50, required=True)), ('page', wagtail.core.blocks.PageChooserBlock(label='A page to be opened')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))])), ('linkcategory', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the category', max_length=50, required=True)), ('stream', wagtail.core.blocks.StreamBlock([('linkblock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(help_text='Name of the link', max_length=50, required=True)), ('page', wagtail.core.blocks.PageChooserBlock(label='A page to be opened')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))])), ('categorychildren', wagtail.core.blocks.StructBlock([('parent', wagtail.core.blocks.PageChooserBlock(label='A page which children should be listed'))]))], label='A nested content of a category')), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('pencil', 'Tužka'), ('people', 'Lidi'), ('info', 'Informace'), ('hand', 'Ruka'), ('child', 'Dítě')], label='The icon'))]))], default=[]),
        ),
    ]
