[project]
name = "phiterm"
version = "0.1.45"
requires-python = ">3.7"
readme = "README.md"
authors = [
  {name = "Ashpreet Bedi", email = "ashpreet@phidata.com"}
]

dependencies = [
    "click",
    "boto3",
    "docker",
    "gitpython",
    "httpx",
    "kubernetes",
    "pydantic",
    "pyyaml",
    "rich",
    "typer",
    "types-PyYAML",
    "typing-extensions",
    "tomli",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
]

[project.urls]
homepage = "https://www.phidata.com"
documentation = "https://www.phidata.com/docs"

[project.scripts]
phi = "phiterm.cli.cli_app:cli_app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
  "git",
  "setuptools",
  "typer",
  "phidata.*",
  "docker.*",
  "docker.models.*",
]
ignore_missing_imports = true
