[tool.poetry]
name = "fifa_pack"
version = "0.0.2"
description = "the package whichcontains utility functions for the main repo"
authors = ["chole Zhang Jinghan Xu Mingting Fu MukeW Wang ShiyangZhang Tony Liang"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.11.1"
bs4 = "^0.0.1"
certifi = "^2022.5.18"
chardet = "^4.0.0"
charset-normalizer = "^2.0.12"
idna = "^3.3"
numpy = "^1.22.4"
pandas = "^1.4.2"
pathlib = "^1.0.1"
python-dateutil = "^2.8.2"
pytz = "^2022.1"
requests = "^2.27.1"
six = "^1.16.0"
soupsieve = "^2.3.2"
urllib3 = "^1.26.9"
google-auth = "^1.12"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
