[tool.poetry]
name = "eve_client"
version = "1.0.2"
description = "EVE API client from Exodus Intelligence LLC."
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/ExodusIntelligence/eve_client"
authors = ["Exodus Intelligence LLC <eng@exodusintel.com>"]

[tool.poetry.dependencies]
python = "^3.7.0"
PyNaCl = "^1.5.0"
python-dateutil = "^2.8.2"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^21.11b1"
isort = "^5.10.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.11.29"
flake8-builtins = "^1.5.3"
darglint = "^1.8.1"
flake8-docstrings = "^1.6.0"
pre-commit = "^2.17.0"
coverage = "^6.3"
requests-mock = "^1.9.3"

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
