[tool.poetry]
name = "e2vec"
version = "0.3.0"
description = ""
authors = ["An Pham <ancs21.ps@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.12"
timm = "^0.5.4"
sentence-transformers = "^2.2.0"
torchaudio = "^0.11.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
