[tool.poetry]
name = "ddcompiler"
version = "1.1.0"
description = "Interpreter for evaluating expressions used in AutomationEdge AIStudio dialog designer"
authors = ["Yogesh Ketkar <yogesh.ketkar@automationedge.com>"]
keywords = ["interpreter, compiler, lexer, parse tree"]
license = "MIT"

readme = "README.md"
homepage = "https://automationedge.com"
repository = "http://bitbucket.org/yovyom/ddcompiler"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
