
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-02T16:41:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a82119b453ee0321c2f66a1d2e12932535d5c032",
 "version": "0.15.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
