# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.geo_json_point_req import GeoJsonPointReq  # noqa: E501
from swagger_client.rest import ApiException


class TestGeoJsonPointReq(unittest.TestCase):
    """GeoJsonPointReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJsonPointReq(self):
        """Test GeoJsonPointReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.geo_json_point_req.GeoJsonPointReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
