# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.note_request import NoteRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestNoteRequest(unittest.TestCase):
    """NoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteRequest(self):
        """Test NoteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.note_request.NoteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
