[tool.poetry]
name = "jsw-bio"
version = "1.0.7"
description = "Jsw for biography."
authors = ["feizheng <1290657123@qq.com>"]
readme = "README.md"
repository = "https://github.com/aric-pypi/jsw-bio"
homepage = "https://js.work"

[tool.poetry.dependencies]
python = "^3.7"
psutil = "^5.9.0"
bs4 = "^0.0.1"
jsw-nx = "^1.0.92"
requests = "^2.27.1"
nltk = "^3.7"
biopython = "^1.79"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
