[tool.poetry]
name = "pastebinpy"
version = "0.1.5"
description = "A Pastebin api created in python with easy to use syntax"
authors = ["Cesiyi <css@amogus.cloud>"]
maintainers = ["Cesiyi <css@amogus.cloud>"]
license = "MIT"
readme = "README.rst"
exclude = ["main.py"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
