[project]
name = "cs.ebooks"
description = "Utilities and command line for working with EBooks. Basic support for talking to Apple Books, Calibre, Kindle, Mobi."
authors = [
    { name = "Cameron Simpson", email = "cs@cskk.id.au" },
]
keywords = [
    "python3",
]
dependencies = [
    "cs.app.osx.plist>=20220606",
    "cs.cmdutils>=20220606",
    "cs.context>=20220227",
    "cs.deco>=20220327",
    "cs.fileutils>=20220429",
    "cs.fs>=20220530",
    "cs.fstags>=20220606",
    "cs.lex>=20220227",
    "cs.logutils>=20220531",
    "cs.numeric>=20190309",
    "cs.obj>=20220530",
    "cs.pfx>=20220523",
    "cs.progress>=20211208",
    "cs.psutils>=20220606",
    "cs.resources>=20220429",
    "cs.sqlalchemy_utils>=20220606",
    "cs.tagset>=20220606",
    "cs.threads>=20211208",
    "cs.units>=20220311",
    "icontract",
    "mobi",
    "os.path",
    "sqlalchemy",
    "typeguard",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
version = "20220606"

[project.license]
text = "GNU General Public License v3 or later (GPLv3+)"

[project.urls]
URL = "https://bitbucket.org/cameron_simpson/css/commits/all"

[project.readme]
text = """
Utilities and command line for working with EBooks.
Basic support for talking to Apple Books, Calibre, Kindle, Mobi.

*Latest release 20220606*:
Initial PyPI release.

These form the basis of my personal Kindle and Calibre workflow.

# Release Log



*Release 20220606*:
Initial PyPI release."""
content-type = "text/markdown"

[build-system]
requires = [
    "setuptools >= 61.0",
    "trove-classifiers",
    "wheel",
]
build-backend = "setuptools.build_meta"
