[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "resume" # import resume

[project]
name = "luke_resume" #As in pip install luke-resume or luke_garzia (pypi will replace _ with -)
authors = [{name = "Luke Garzia", email = "garzia.luke@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"] # description doc string of package
readme = "README.md"
requires-python = ">=3.7"
dependencies = ['click >8.0.0', 'typer']


[project.urls]
Home = "https://github.com/lgarzia/resume"

[project.scripts]
luke     = "resume.__main__:main" #luke command will can the main() in __main__.py
resume = "resume.__main__:main"

[project.optional-dependencies]
test = ["mypy", "black", "flake8", "isort", "flake8-comprehensions", "pre-commit",
"pytest", "pytest-cov", "interrogate", "tox"]
doc = ["sphinx", "myst-nb", "sphinx-rtd-theme", "sphinx-autoapi"]

[tool.isort]
multi_line_output = 3
profile = "black"
import_heading_stdlib     = "Standard library imports"
import_heading_thirdparty = "Third party imports"
import_heading_firstparty = "resume imports"
