import h5py as h5
import numpy as np
import typing as tp
from typing import Any

def linspace(start, end, count: int): ...
def meshcorners(corners: np.ndarray, grid: tp.Tuple): ...
def cutpatch(data: tp.Union[np.ndarray, h5.Dataset], corners: np.ndarray, grid: tuple, fill: Any | None = ...) -> np.ndarray: ...
