[tool.poetry]
name = "scrapekit"
version = "0.3.0"
description = "Modular scraping convenience framework written in Python."
authors = ["C. Weber <c@omniviant.com>"]
maintainers = ["C. Weber <c@omniviant.com>"]
repository = "https://bitbucket.org/chad-og/scrapekit/"
readme = "README.md"
keywords = [
    "Web scraping",
    "Scraping",
    "IP Burger",
    "Proxy",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
