[tool.poetry]
name = "intentron"
version = "0.1.7"
description = ""
authors = ["catsudo <catsudo@nous.dev>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
alive-progress = "^2.4.1"
click = "^8.1.3"
loguru = "^0.6.0"
opencv-python = "^4.5.5"
pandas = "^1.4.2"
matplotlib = "^3.5.2"
mediapipe = ">=0.8"
scikit-learn = "^1.1.1"
scipy = "^1.8.1"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
