
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T17:08:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b077768e91d9cc140a29ec5a2065cfa02d9c0fc",
 "version": "0.2.3.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
