[tool.poetry]
name = "nonebot_plugin_R3nzSkin"
version = "0.1.0"
description = ""
authors = ["Aa <2272613209@qq.com>"]

[tool.poetry.dependencies]
python = "^3.10"
nonebot-adapter-onebot = "^2.1.0"
nonebot-plugin-apscheduler = "^0.1.2"
httpx = "^0.23.0"
Pillow = "^9.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
nb-cli = "^0.6.7"
black = {version = "^22.3.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
