[tool.poetry]
name = "arkhamdb"
version = "0.0.7"
authors = ["James Veitch <1722315+darth-veitcher@users.noreply.github.com>"]
description = "Pythonic wrapper around the excellent ArkhamDB API. Designed to be standalone and importable to other projects."
documentation = "https://arkhamdb.readthedocs.io"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
httpx = "^0.22.0"
importlib-metadata = {version = "^4.11.3", python = "<3.8"}
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = ">=5.2"
pylama = {extras = ["lint"], version = "^8.3.8"}
black = "^22.3.0"
pyproject-flake8 = "^0.0.1-alpha.4"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
coverage = {extras = ["toml"], version = "^6.3.3"}
nox = "^2022.1.7"
pytest-mock = "^3.7.0"
mock = "^4.0.3"
jupyter = "^1.0.0"
notebook = "^6.4.11"
pycodestyle = "^2.8.0"
flake8 = "^4.0.1"
flake8-black = "^0.3.3"
isort = "^5.10.1"
flake8-isort = "^4.1.1"
flake8-bandit = "^3.0.0"
pre-commit = "^2.19.0"
mypy = "^0.950"
typed-ast = "^1.5.3"
pytype = {version = "^2022.5.10", python = "3.7"}
flake8-docstrings = "^1.6.0"
flake8-annotations = "^2.9.0"
darglint = "^1.8.1"
Sphinx = "^4.5.0"
sphinxcontrib-napoleon = "^0.7"
sphinx-autodoc-typehints = "^1.18.1"
myst-parser = "^0.17.2"
toml = "^0.10.2"
sphinx-autobuild = "^2021.3.14"
sphinxawesome-theme = "^3.3.0"
sphinxcontrib-programoutput = "^0.17"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arkhamdb = "arkhamdb.console:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["arkhamdb"]
omit = ["*tests*", "*migrations*"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.pytest.ini_options]
asyncio_mode = "auto"
mock_use_standalone_module = "true"

[tool.isort]
profile = "black"
src_paths = ["arkhamdb", "tests"]
skip = ["build",".nox",".venv",".git","__pycache__"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "mypy-nox.*",
    "pytest",
    "click",
    "click.*",
    "httpx",
    "httpx.*",
    "mock",
    "pytest_mock",
    "nox",
    "importlib.metadata",
    "importlib_metadata",
    "pydantic",
    "pytest_asyncio"
]
ignore_missing_imports = true
