# Generated by Django 4.0 on 2022-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nextflow', '0003_data_is_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='data_params',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_params',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='execution',
            name='params',
            field=models.TextField(default='{}'),
        ),
    ]
