# This workflow will upload a Python Package using Twine when a release is created
# See https://scikit-hep.org/developer/gha_pure

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build SDist and wheel
      run: pipx run build

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*

    - name: Check metadata
      run: pipx run twine check dist/*

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
