
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T08:29:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1ce97cda5636ad0263cb0669e4cb4a56cc52a9f",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
