[tool.poetry]
name = "pyventure"
version = "0.1.0"
description = "A simple framework for creating text adventure games."
authors = ["David Flood <davidfloodii@gmail.com>"]
license = "MIT"
readme = "readme.md"
repository = "https://github.com/d-flood/pyventure"
homepage = "https://github.com/d-flood/pyventure"


[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
