[tool.poetry]
name = "dotjson"
version = "0.1.2"
description = "Read key-value pairs from a settings.json file and set them as environment variables, dictionary or Pydantic models"
authors = ["Aakash Khanna <aakashkh13@gmail.com>"]
readme="README.md"
repository="https://github.com/aakashkhanna/python-dotjson"
documentation="https://github.com/aakashkhanna/python-dotjson#readme"
classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Operating System :: OS Independent',
        'Topic :: System :: Systems Administration',
        'Topic :: Utilities',
        'Environment :: Web Environment',
    ]

[tool.poetry.dependencies]
python = "^3.8"
flatten-json = "^0.1.13"
pydantic = "^1.9.1"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-md-report = "^0.2.0"

[tool.pytest.ini_options]
addopts = "/project/tests/ -q tests --md-report --md-report-verbose=1  --md-report-color never --cov=dotjson"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
