[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=47",
    "wheel>=0.34",
]

[tool.black]
line-length = 79

[tool.mypy]

exclude = [
    'alembic/template',
    'alembic.testing.*',
]
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    'mako.*',
    'sqlalchemy.testing.*'
]
ignore_missing_imports = true
