
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T13:17:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3c2e0547a4009fac6645deeea7ec3e1a125ef40",
 "version": "0.2.3.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
