[tool.poetry]
name = "fastapi_interface"
version = "0.2.0"
description = "for DRY in microservices"
authors = ["koevgeny10 <koevgeny10@gmail.com>"]
packages = [{ include = "fastapi_interface", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"

fastapi = "^0.78.0"
email-validator = "^1.2.1"
python-multipart = "^0.0.5"
orjson = "^3.6.8"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tenacity = "*"
requests = "^2.27.1"

pre-commit = "^2.18.1"

ipython = "^8.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
