services: 

  agent_service:
    build: .
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: agent_service_db
      DB_PORT: 5432
      DB_NAME: postgres
      DATABASE_URL: postgresql://postgres:postgres@agent_service_db:5432/postgres
    networks:
      - dislinkt
    ports:
      - 8011:8011

  agent_service_db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgres/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dislinkt
    ports:
      - 5437:5432

networks:
  dislinkt:

volumes:
  postgres:
