[tool.poetry]
name = "gitreturn"
version = "1.1.0"
description = "Script to return to staging."
license = "MIT"
authors = ["blackboardd <brightenqtompkins@gmail.com>"]

[tool.poetry.scripts]
git_return = "gitreturn.cli:run"

[tool.poetry.dependencies]
python = "^3.7"
PyInquirer = "^1.0.3"
requests = "^2.27.1"
