
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T12:59:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0a8e41cd36d675b7f7db101541ac44050f26efa",
 "version": "0.2.4.post0.dev21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
