# Package Overview
package_name: titanic_survivor

# Data Files
raw_data_file: raw.csv
test_data_file: test.csv

# Pipeline
pipeline_name: titanic_model
pipeline_save_file: titanic_model_output_v

# Variables
# The variable we are attempting to predict (sale price)
target: survived
variable_to_get_first_letter: cabin
variable_to_get_salutation: name
variable_to_create: title
features:
  - age
  - fare
  - pclass
  - sex
  - sibsp
  - parch
  - cabin
  - embarked
  - name
categorical_vars:
  - sex
  - cabin
  - embarked
  - title
numerical_vars:
  - age
  - fare

test_size: 0.1
random_state: 1
penalty: 0.0005

