# coding: utf-8

"""
    Component Database API

    The API that provides access to Component Database data.  # noqa: E501

    The version of the OpenAPI document: 3.14.0
    Contact: djarosz@anl.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cdbApi.configuration import Configuration


class MachineDesignConnectorListObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'item_connector': 'ItemConnector',
        'cable_item': 'ItemDomainCableDesign',
        'connected_to_items_list': 'list[ItemDomainMachineDesign]',
        'connected_to_items_string': 'str',
        'cable_relationship': 'ItemElementRelationship',
        'connector_name': 'str',
        'cable_name': 'str'
    }

    attribute_map = {
        'item_connector': 'itemConnector',
        'cable_item': 'cableItem',
        'connected_to_items_list': 'connectedToItemsList',
        'connected_to_items_string': 'connectedToItemsString',
        'cable_relationship': 'cableRelationship',
        'connector_name': 'connectorName',
        'cable_name': 'cableName'
    }

    def __init__(self, item_connector=None, cable_item=None, connected_to_items_list=None, connected_to_items_string=None, cable_relationship=None, connector_name=None, cable_name=None, local_vars_configuration=None):  # noqa: E501
        """MachineDesignConnectorListObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._item_connector = None
        self._cable_item = None
        self._connected_to_items_list = None
        self._connected_to_items_string = None
        self._cable_relationship = None
        self._connector_name = None
        self._cable_name = None
        self.discriminator = None

        if item_connector is not None:
            self.item_connector = item_connector
        if cable_item is not None:
            self.cable_item = cable_item
        if connected_to_items_list is not None:
            self.connected_to_items_list = connected_to_items_list
        if connected_to_items_string is not None:
            self.connected_to_items_string = connected_to_items_string
        if cable_relationship is not None:
            self.cable_relationship = cable_relationship
        if connector_name is not None:
            self.connector_name = connector_name
        if cable_name is not None:
            self.cable_name = cable_name

    @property
    def item_connector(self):
        """Gets the item_connector of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The item_connector of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: ItemConnector
        """
        return self._item_connector

    @item_connector.setter
    def item_connector(self, item_connector):
        """Sets the item_connector of this MachineDesignConnectorListObject.


        :param item_connector: The item_connector of this MachineDesignConnectorListObject.  # noqa: E501
        :type: ItemConnector
        """

        self._item_connector = item_connector

    @property
    def cable_item(self):
        """Gets the cable_item of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The cable_item of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: ItemDomainCableDesign
        """
        return self._cable_item

    @cable_item.setter
    def cable_item(self, cable_item):
        """Sets the cable_item of this MachineDesignConnectorListObject.


        :param cable_item: The cable_item of this MachineDesignConnectorListObject.  # noqa: E501
        :type: ItemDomainCableDesign
        """

        self._cable_item = cable_item

    @property
    def connected_to_items_list(self):
        """Gets the connected_to_items_list of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The connected_to_items_list of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: list[ItemDomainMachineDesign]
        """
        return self._connected_to_items_list

    @connected_to_items_list.setter
    def connected_to_items_list(self, connected_to_items_list):
        """Sets the connected_to_items_list of this MachineDesignConnectorListObject.


        :param connected_to_items_list: The connected_to_items_list of this MachineDesignConnectorListObject.  # noqa: E501
        :type: list[ItemDomainMachineDesign]
        """

        self._connected_to_items_list = connected_to_items_list

    @property
    def connected_to_items_string(self):
        """Gets the connected_to_items_string of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The connected_to_items_string of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: str
        """
        return self._connected_to_items_string

    @connected_to_items_string.setter
    def connected_to_items_string(self, connected_to_items_string):
        """Sets the connected_to_items_string of this MachineDesignConnectorListObject.


        :param connected_to_items_string: The connected_to_items_string of this MachineDesignConnectorListObject.  # noqa: E501
        :type: str
        """

        self._connected_to_items_string = connected_to_items_string

    @property
    def cable_relationship(self):
        """Gets the cable_relationship of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The cable_relationship of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: ItemElementRelationship
        """
        return self._cable_relationship

    @cable_relationship.setter
    def cable_relationship(self, cable_relationship):
        """Sets the cable_relationship of this MachineDesignConnectorListObject.


        :param cable_relationship: The cable_relationship of this MachineDesignConnectorListObject.  # noqa: E501
        :type: ItemElementRelationship
        """

        self._cable_relationship = cable_relationship

    @property
    def connector_name(self):
        """Gets the connector_name of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The connector_name of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: str
        """
        return self._connector_name

    @connector_name.setter
    def connector_name(self, connector_name):
        """Sets the connector_name of this MachineDesignConnectorListObject.


        :param connector_name: The connector_name of this MachineDesignConnectorListObject.  # noqa: E501
        :type: str
        """

        self._connector_name = connector_name

    @property
    def cable_name(self):
        """Gets the cable_name of this MachineDesignConnectorListObject.  # noqa: E501


        :return: The cable_name of this MachineDesignConnectorListObject.  # noqa: E501
        :rtype: str
        """
        return self._cable_name

    @cable_name.setter
    def cable_name(self, cable_name):
        """Sets the cable_name of this MachineDesignConnectorListObject.


        :param cable_name: The cable_name of this MachineDesignConnectorListObject.  # noqa: E501
        :type: str
        """

        self._cable_name = cable_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MachineDesignConnectorListObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MachineDesignConnectorListObject):
            return True

        return self.to_dict() != other.to_dict()
