[build-system]
requires = [
    "setuptools>=42",
    "wheel",
	"Faker==11.3.0",
	"psycopg2>=2.9.3",
	"python-dateutil==2.8.2",
	"six==1.16.0",
	"text-unidecode==1.3",
	"faker-vehicle==0.2.0",
]
build-backend = "setuptools.build_meta"