[tool.poetry]
name = "detaMVC"
version = "0.1.7"
description = ""
authors = ["MBeebe <grow.food.everywhere@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
detamvc = "detamvc.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.4.1"}
fastapi = "*"
jinja2 = "*"
deta = "*"
odetam = "*"
python-multipart = "*"
python-dotenv = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
