
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T15:39:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d07fb7599de1c89beb7c5afe500b34452ec8fc45",
 "version": "0.7.1.post.dev588"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
