[tool.poetry]
name = "curses-playlist"
version = "0.1.1"
description = "curses based interactive playlist creation for videos"
authors = ["dominicmai <dr.dosn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
windows-curses = "^2.3.0"
moviepy = "^1.0.3"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
plist = 'plist.plist:main'