[tool.poetry]
name = "recline"
version = "2022.6"
description = "Writing argparse-based command line applications can become tedious, repetitive, and difficult to do right. Relax and let this library free you from that burden."
license = "BSD-3-Clause"
authors = ["NetApp <ng-netapp-oss@netapp.com>"]
readme = "README.md"

homepage = "https://github.com/NetApp/recline"
repository = "https://github.com/NetApp/recline"
documentation = "https://netapp.github.io/recline"
keywords = ["cli", "interactive", "shell", "argparse", "recline"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Shells",
]

packages = [
    { include = "recline" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.6,<4"
pyreadline = {version = "^2.1", markers = "sys_platform == 'win32'"}
windows-curses = {version = "^2.3.0", markers = "sys_platform == 'win32'"}

[tool.poetry.dev-dependencies]
pudb = "^2022.1.1"
pylint = "^2.5.2"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-apidoc = "^0.3.0"
