
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-01T12:47:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "49a4bcded7e0a50621f2efa79145dd2d60a87332",
 "version": "v4.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
