[build-system]
requires = [
	"setuptools",
	"setuptools-scm",
    "oldest-supported-numpy; python_version>='3.5'"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp38-*"
skip = "cp38-manylinux_[aps]*"
