[tool.poetry]
name = "ariel-client-triton"
version = "0.1.0"
description = "Client utilities for the triton inference server"
authors = ["Luis Vega <vegaluisjose@gmail.com>", "Jared Roesch <jroesch@octoml.ai>"]
packages = [
    { include = "ariel" }
]

[tool.poetry.dependencies]
python = ">=3.6"
grpcio = "~1.41.0" # pinned to tritonclient's version
tritonclient = {version = "^2.22.0", extras= ["all"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
