[tool.poetry]
name = "nba_bbref_webscrape"
version = "0.0.6"
description = "Scraping basketball-reference.com w/ Pandas and BeautifulSoup4"
authors = ["jyablonski9 <jyablonski9@gmail.com>"]

homepage = "https://github.com/jyablonski/nba_bbref_webscrape"
repository = "https://github.com/jyablonski/nba_bbref_webscrape"

[tool.poetry.dependencies]
python = "^3.8, <3.9"
pandas = "1.3.5"
SQLAlchemy = "^1.4.37"
nltk = "^3.7"
psycopg2-binary = "^2.9.3"
requests = "2.27.1"
boto3 = "1.21.8"
awswrangler = "2.14.0"
sentry-sdk = "1.5.8"
beautifulsoup4 = "4.9.3"
praw = "7.5.0"
lxml = "4.8.0"
html5lib = "1.1"
PyYAML = "5.4.1"
twint = "2.1.20"


[tool.poetry.dev-dependencies]
pytest = "7.0.1"
moto = "2.2.17"
pytest-cov = "3.0.0"
pytest-mock = "3.7.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
