[project]
name = "pons"
version = "0.4.2"
description = "Async RPC client for Ethereum"
authors = [
    { name = "Bogdan Opanchuk", email = "bogdan@opanchuk.net" },
]
dependencies = [
    "httpx>=0.22",
    "eth-account>=0.5",
    "eth-utils>=1.10",
    "eth-abi>=2",
    "anyio>=3",
    "setuptools",
]
requires-python = ">=3.8"
license-expression = "MIT"
readme = "README.md"

[project.urls]
homepage = "https://github.com/fjarri/pons"

[project.optional-dependencies]
tests = [
    "pytest>=6",
    "trio>=0.19.0",
    "pytest-trio",
    "pytest-cov",
    "py-solc-x>=1",
    "eth-tester[pyevm]",
    "starlette",
    "hypercorn",
]
docs = [
    "sphinx>=4",
    "furo",
    "sphinxcontrib-trio",
]
lint = [
    "mypy>=0.941",
    "trio-typing[mypy]>=0.7.0",
    "black",
]

[tool.black]
line-length = 100
target-version = [
    "py38",
]

[tool.pdm.dev-dependencies]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"
