[tool.poetry]
name = "flask_admin_plus"
version = "1.6.1"
description = "Flask Admin with a few more features and improvements"
authors = ["Sean McCarthy <smccarthy@myijack.com>"]
packages = [
    { include = "flask_admin" },
]

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.5.2"
autoflake = "^1.4"
flake8 = "^3.8.3"
bandit = "^1.6.2"
pylint = "^2.6.0"
pytest = "^6.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
