[tool.poetry]
name = "royalnet-discordpy"
version = "6.6.4"
description = "A Discord.py-based frontend for the royalnet.engineer module."
authors = ["Stefano Pigozzi <me@steffo.eu>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/Steffo99/royalnet-discordpy"
documentation = "https://royalnet-discordpy.readthedocs.io/"
keywords = ["royalnet"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.dependencies]
python = "^3.10"
royalnet = "^6.7.1"
click = "^7.1.2"
"discord.py" = "^1.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-asyncio = "^0.15.0"
sphinx = "^3.3.1"
sphinx_rtd_theme = "^0.5.0"

[tool.pytest.ini_options]
minversion = "6.0"
log_cli = true
log_cli_level = "DEBUG"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
