
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T14:43:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd4917700cec1685aef29aa18610e15ceb4d9890",
 "version": "2679"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
