
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T13:02:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "125500b877114a3efb01ff4c892c3584c3ceac1f",
 "version": "0.9.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
