name: moosir-feature-dev

dependencies:
  - python=3.7
  - pyscaffold
  - tox
  - typing-extensions
  - pre_commit
  - pytest-cov
  - pytest
  - pytables # todo: for saving h5 it s needed (pip doesnot work!!)
#  - todo: wtf
  - ta-lib
  - pip

