[tool.poetry]
name = "some_models"
version = "0.3.0"
description = "Учебная библиотека. Тут находятся orm модели нужные в нескольких микросервисах, что бы не нарушать DRY."
authors = ["koevgeny10 <koevgeny10@gmail.com>"]
packages = [{ include = "some_models", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9"
SQLAlchemy = "^1.4.33"

#[tool.poetry.group.migrations]
#optional = true
#[tool.poetry.group.migrations.dependencies]
#pydantic = "^1.9.1"
#alembic = "^1.7.7"
#
#[tool.poetry.group.tests]
#optional = true
#[tool.poetry.group.tests.dependencies]
#pytest = "^7.1.2"

#[tool.poetry.group.dev]
#optional = true
#[tool.poetry.group.dev.dependencies]
[tool.poetry.dev-dependencies]
pre-commit = "^2.18.1"
ipython = "^8.3.0"

pydantic = "^1.9.1"
alembic = "^1.7.7"

pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
