
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T08:58:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "99741c1ccb361a763be63d10e42a7fa80943c372",
 "version": "1.16.0.post.dev614"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
