[tool.poetry]
authors = ["Craig Trim <craig@grafflr.ai>"]
description = "Base Block of Common Enterprise Python Utilities"
name = "baseblock"
version = "0.1.2"

[tool.poetry.dependencies]
PyYAML = "6.0"
cryptography = "37.0.2"
plac = "*"
python = "3.8.5"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
pytest = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
