[tool.poetry]
name = "gitrestore"
version = "0.0.2"
description = "Script to return to staging."
license = "MIT"
authors = ["blackboardd <brightenqtompkins@gmail.com>"]

[tool.poetry.scripts]
gitr = "gitr:run"

[tool.poetry.dependencies]
python = "^3.7"
PyInquirer = "^1.0.3"
