[tool.poetry]
name = "django3-flatpages-tinymce"
version = "0.2.2"
description = "HTML editor on django.contrib.flatpages"
authors = ["Scott Sharkey <ssharkey@lanshark.com>"]
license = "MIT"
packages = [ { include = "flatpages_tinymce" } ]
readme = "README.md"
repository = "https://gitlab.com/lansharkconsulting/django/django3-flatpages-tinymce"
homepage = "https://gitlab.com/lansharkconsulting/django/django3-flatpages-tinymce"
keywords = [ "django", "flatpages", "tinymce", "WYSIWYG" ]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Environment :: Web Environment",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Operating System :: POSIX",
        "Operating System :: Unix",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Internet :: WWW/HTTP :: Site Management",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Framework :: Django",
        "Framework :: Django :: 3.0",
        "Framework :: Django :: 3.1",
        "Framework :: Django :: 3.2",
        "Framework :: Django :: 4.0",
]
include = [
    "LICENSE",
    "CHANGELOG.md",
    "flatpages_tinymce/templates/*",
    "flatpages_tinymce/static/*",
    ".gitignore",
]

[tool.poetry.dependencies]
python = "^3.7"
Django = ">=3.0"
django_tinymce = ">=1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
