
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-01T13:36:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "06fbfcc571de1e52ba84101b8441ce0e5cae8bf7",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
