
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-01T16:03:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b39342a0d336cf9548f3a61fd6d4867417f59930",
 "version": "2022.05"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
