
# Names
PIPELINE_NAME: SentimentModel
PACKAGE_SAVE_FILE: SentimentModel_output_v
DATA_FILE_PATH: data/training.1600000.processed.noemoticon.csv
MODELS_PATH: models/

MODEL_NAME: Model_v1
TOKENIZER_NAME: Tokenizer_v1.pkl
CLASSES_NAME: Classes_v1.pkl
EMBEDDED_MATRIX_NAME: Embedded_matrix_v1.pkl



# dataset configs
DATASET_COLUMNS:
  - sentiment
  - ids
  - date
  - flag
  - user
  - text
DATASET_ENCODING: ISO-8859-1


TARGET: sentiment
NEUTRAL_THRESHOLD: 0.7
CLASSES: 
  - NEGATIVE
  - NEUTRAL 
  - POSITIVE
NEGATIVE_INDEX: 0
NEUTRAL_INDEX: 1
POSITIVE_INDEX: 2

# To replicate the results
SEED: 42



# Model params
TEST_SIZE: 0.1
INPUT_LEN: 60
VOCAB_LEN: 60000
EMBEDDING_DIMENSIONS: 100
EPOCHS: 4
BATCH_SIZE: 1024
