[tool.poetry]
name = "nlp-service"
version = "0.3.0"
description = "Microservice for NLP tasks using gRPC"
authors = ["Mirko Lenz <info@mirko-lenz.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "http://recap.uni-trier.de"
repository = "https://github.com/ReCAP-UTR/NLP"

[tool.poetry.scripts]
nlp-service = "nlp_service.server:app"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.2"
scipy = "^1.8.0"
spacy = "^3.2.1"
grpcio = "^1.43.0"
arg-services = "^0.3.6"
tensorflow = { version = "^2.8.0", optional = true }
sentence-transformers = { version = "^2.1.0", optional = true }
tensorflow-hub = { version = "^0.12.0", optional = true }
gensim = { version = "^4.1.2", optional = true }
pyemd = { version = "^0.5.1", optional = true }
typer = { version = "^0.4.0", optional = true }
python-Levenshtein = { version = "^0.12.2", optional = true }
torch = { version = "^1.10.2", optional = true }
nltk = "^3.6.7"
dataclasses-json = "^0.5.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
wmd = ["gensim"]
server = [
    "sentence-transformers",
    "tensorflow",
    "tensorflow-hub",
    "gensim",
    "python-levenshtein",
    "typer",
    "pyemd",
    "torch",
]
