name: Create Rust release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'rs-v*' # Push events to matching rs-v*, i.e. rs-v1.0, rs-v20.15.10
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  rust_release:
    name: Rust Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: to workdir
        run: cd fastbloom-rs
      - name: package
        run: cargo package
      - name: publish
        run: cargo publish
