[package]
name = "rust-pyspec-glue"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_pyspec_glue"
crate-type = ["cdylib"]

[dependencies]
#ethereum-pyspec-db = { git = "https://github.com/petertdavies/rust-pyspec-db.git" , rev = "74587373c43abc6d32d0174d395c0f003118bd77"}
ethereum-pyspec-db = { git = "https://github.com/petertdavies/rust-pyspec-db" }
ethereum-types = "0.12.1"

[package.metadata.maturin]
python-source = "python"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
