
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-02T23:24:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7092deb6d5e80b7dab34c7fad5d36613ee54fbcc",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
