
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "full": "21.1.0rc1",
 "version": "21.1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
