
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-31T10:30:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "63c94c84a059fe17d8a9e624cf91ddd5099a29c4",
 "version": "v0.1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
