# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class BoundaryAggregateControllerApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_largest_and_smallest_plot_using_get(self, tenant_type, **kwargs):  # noqa: E501
        """getLargestAndSmallestPlot  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_largest_and_smallest_plot_using_get(tenant_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_type: TenantType (required)
        :param str boundary_aggregate_type:
        :param str boundary_id:
        :param str boundary_type:
        :param str current_level:
        :param str direction:
        :param datetime end_date_time:
        :param list[str] ids:
        :param datetime max_created_date_time:
        :param datetime max_modified_date_time:
        :param datetime min_created_date_time:
        :param datetime min_modified_date_time:
        :param str org_id: orgId
        :param int page:
        :param list[str] select:
        :param int size:
        :param str sort_by:
        :param str status:
        :param list[str] statuses:
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_largest_and_smallest_plot_using_get_with_http_info(tenant_type, **kwargs)  # noqa: E501
        else:
            (data) = self.get_largest_and_smallest_plot_using_get_with_http_info(tenant_type, **kwargs)  # noqa: E501
            return data

    def get_largest_and_smallest_plot_using_get_with_http_info(self, tenant_type, **kwargs):  # noqa: E501
        """getLargestAndSmallestPlot  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_largest_and_smallest_plot_using_get_with_http_info(tenant_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tenant_type: TenantType (required)
        :param str boundary_aggregate_type:
        :param str boundary_id:
        :param str boundary_type:
        :param str current_level:
        :param str direction:
        :param datetime end_date_time:
        :param list[str] ids:
        :param datetime max_created_date_time:
        :param datetime max_modified_date_time:
        :param datetime min_created_date_time:
        :param datetime min_modified_date_time:
        :param str org_id: orgId
        :param int page:
        :param list[str] select:
        :param int size:
        :param str sort_by:
        :param str status:
        :param list[str] statuses:
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tenant_type', 'boundary_aggregate_type', 'boundary_id', 'boundary_type', 'current_level', 'direction', 'end_date_time', 'ids', 'max_created_date_time', 'max_modified_date_time', 'min_created_date_time', 'min_modified_date_time', 'org_id', 'page', 'select', 'size', 'sort_by', 'status', 'statuses']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_largest_and_smallest_plot_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'tenant_type' is set
        if self.api_client.client_side_validation and ('tenant_type' not in params or
                                                       params['tenant_type'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `tenant_type` when calling `get_largest_and_smallest_plot_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'boundary_aggregate_type' in params:
            query_params.append(('boundaryAggregateType', params['boundary_aggregate_type']))  # noqa: E501
        if 'boundary_id' in params:
            query_params.append(('boundaryId', params['boundary_id']))  # noqa: E501
        if 'boundary_type' in params:
            query_params.append(('boundaryType', params['boundary_type']))  # noqa: E501
        if 'current_level' in params:
            query_params.append(('currentLevel', params['current_level']))  # noqa: E501
        if 'direction' in params:
            query_params.append(('direction', params['direction']))  # noqa: E501
        if 'end_date_time' in params:
            query_params.append(('endDateTime', params['end_date_time']))  # noqa: E501
        if 'ids' in params:
            query_params.append(('ids', params['ids']))  # noqa: E501
            collection_formats['ids'] = 'multi'  # noqa: E501
        if 'max_created_date_time' in params:
            query_params.append(('maxCreatedDateTime', params['max_created_date_time']))  # noqa: E501
        if 'max_modified_date_time' in params:
            query_params.append(('maxModifiedDateTime', params['max_modified_date_time']))  # noqa: E501
        if 'min_created_date_time' in params:
            query_params.append(('minCreatedDateTime', params['min_created_date_time']))  # noqa: E501
        if 'min_modified_date_time' in params:
            query_params.append(('minModifiedDateTime', params['min_modified_date_time']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'select' in params:
            query_params.append(('select', params['select']))  # noqa: E501
            collection_formats['select'] = 'multi'  # noqa: E501
        if 'size' in params:
            query_params.append(('size', params['size']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sortBy', params['sort_by']))  # noqa: E501
        if 'status' in params:
            query_params.append(('status', params['status']))  # noqa: E501
        if 'statuses' in params:
            query_params.append(('statuses', params['statuses']))  # noqa: E501
            collection_formats['statuses'] = 'multi'  # noqa: E501

        header_params = {}
        if 'org_id' in params:
            header_params['orgId'] = params['org_id']  # noqa: E501
        if 'tenant_type' in params:
            header_params['TenantType'] = params['tenant_type']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['JWT']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/boundaryaggregate/largestandsmallestplot', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
